export const pagesRoutes = [
  ["v-2ff80a47","/AboutUs.html",{"title":"About Us"},[":md"]],
  ["v-f8039104","/Advanced.html",{"title":"Advanced"},[":md"]],
  ["v-39a2059c","/FAQ.html",{"title":"Frequently Asked Questions"},[":md"]],
  ["v-1eb00f35","/GetStarted.html",{"title":"Installation"},[":md"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/README.md"]],
  ["v-5bd8e7d6","/Roles.html",{"title":"Roles"},[":md"]],
  ["v-0bfd6e38","/options/Settings/Addons.html",{"title":"Add-ons"},[":md"]],
  ["v-3bd8288e","/options/Settings/Crewmates.html",{"title":"Crewmates"},[":md"]],
  ["v-3ebcba66","/options/Settings/Custom.html",{"title":"Custom Settings"},[":md"]],
  ["v-404e0662","/options/Settings/Experimental.html",{"title":"Experimental"},[":md"]],
  ["v-eab3bbf6","/options/Settings/Game.html",{"title":"Game Settings"},[":md"]],
  ["v-21df66e2","/options/Settings/Impostors.html",{"title":"Impostors"},[":md"]],
  ["v-b7336a82","/options/Settings/Modifiers.html",{"title":"Game Modifiers"},[":md"]],
  ["v-2db263ab","/options/Settings/Neutrals.html",{"title":"Neutrals"},[":md"]],
  ["v-4d2f5a68","/options/Settings/System.html",{"title":"System Settings"},[":md"]],
  ["v-af508636","/options/Addons/Harmful/Disregarded.html",{"title":"Disregarded"},[":md"]],
  ["v-156447a1","/options/Addons/Harmful/Fragile.html",{"title":"Fragile"},[":md"]],
  ["v-48f47b27","/options/Addons/Harmful/Oblivious.html",{"title":"Oblivious"},[":md"]],
  ["v-511019b7","/options/Addons/Harmful/Rascal.html",{"title":"Rascal"},[":md"]],
  ["v-6a26a203","/options/Addons/Harmful/Sunglasses.html",{"title":"Sunglasses"},[":md"]],
  ["v-4e13bf82","/options/Addons/Harmful/Unlucky.html",{"title":"Unlucky"},[":md"]],
  ["v-2d08a8c9","/options/Addons/Harmful/VoidBallot.html",{"title":"Void Ballot"},[":md"]],
  ["v-6a019bf7","/options/Addons/Helpful/Autopsy.html",{"title":"Autopsy"},[":md"]],
  ["v-2afe320a","/options/Addons/Helpful/Bait.html",{"title":"Bait"},[":md"]],
  ["v-7a81cfb3","/options/Addons/Helpful/Beartrap.html",{"title":"Beartrap"},[":md"]],
  ["v-3622e43a","/options/Addons/Helpful/Bewilder.html",{"title":"Bewilder"},[":md"]],
  ["v-9f3cbb04","/options/Addons/Helpful/Burst.html",{"title":"Burst"},[":md"]],
  ["v-e0adda36","/options/Addons/Helpful/Cyber.html",{"title":"Cyber"},[":md"]],
  ["v-b78b24ae","/options/Addons/Helpful/DoubleShot.html",{"title":"Double Shot"},[":md"]],
  ["v-fd069b00","/options/Addons/Helpful/Lazy.html",{"title":"Lazy"},[":md"]],
  ["v-5a128386","/options/Addons/Helpful/Loyal.html",{"title":"Loyal"},[":md"]],
  ["v-f3366494","/options/Addons/Helpful/Lucky.html",{"title":"Lucky"},[":md"]],
  ["v-79a35ef0","/options/Addons/Helpful/Necroview.html",{"title":"Necroview"},[":md"]],
  ["v-697cc36a","/options/Addons/Helpful/Nimble.html",{"title":"Nimble"},[":md"]],
  ["v-134ca5a5","/options/Addons/Helpful/Overclocked.html",{"title":"Overclocked"},[":md"]],
  ["v-33b5d291","/options/Addons/Helpful/Repairman.html",{"title":"Repairman"},[":md"]],
  ["v-67e8b356","/options/Addons/Helpful/Seer.html",{"title":"Seer"},[":md"]],
  ["v-5078afd7","/options/Addons/Helpful/Sleuth.html",{"title":"Sleuth"},[":md"]],
  ["v-6a389150","/options/Addons/Helpful/Tiebreaker.html",{"title":"Tiebreaker"},[":md"]],
  ["v-01132122","/options/Addons/Helpful/Torch.html",{"title":"Torch"},[":md"]],
  ["v-4ea01622","/options/Addons/Helpful/Watcher.html",{"title":"Watcher"},[":md"]],
  ["v-1940aa7f","/options/Addons/Impostor/Circumvent.html",{"title":"Circumvent"},[":md"]],
  ["v-a4efd4c8","/options/Addons/Impostor/Clumsy.html",{"title":"Clumsy"},[":md"]],
  ["v-5ebbf566","/options/Addons/Impostor/LastImpostor.html",{"title":"Last Impostor"},[":md"]],
  ["v-93f320cc","/options/Addons/Impostor/Madmate.html",{"title":"Madmate"},[":md"]],
  ["v-3ec6cc3c","/options/Addons/Impostor/Mare.html",{"title":"Mare"},[":md"]],
  ["v-5fa36c04","/options/Addons/Impostor/Mimic.html",{"title":"Mimic"},[":md"]],
  ["v-659c4613","/options/Addons/Impostor/Stealer.html",{"title":"Stealer"},[":md"]],
  ["v-13e5221c","/options/Addons/Impostor/Swift.html",{"title":"Swift"},[":md"]],
  ["v-27dfbf49","/options/Addons/Miscellaneous/Egoist.html",{"title":"Egoist"},[":md"]],
  ["v-142b6d33","/options/Addons/Miscellaneous/Lovers.html",{"title":"Lovers"},[":md"]],
  ["v-5a35700e","/options/Addons/Miscellaneous/Reach.html",{"title":"Reach"},[":md"]],
  ["v-2169ac20","/options/Addons/Miscellaneous/Workhorse.html",{"title":"Workhorse"},[":md"]],
  ["v-281456b5","/options/Addons/Mixed/Antidote.html",{"title":"Antidote"},[":md"]],
  ["v-7ed05ea9","/options/Addons/Mixed/Avenger.html",{"title":"Avenger"},[":md"]],
  ["v-b46d1c7e","/options/Addons/Mixed/Aware.html",{"title":"Aware"},[":md"]],
  ["v-3a19de3b","/options/Addons/Mixed/Bloodlust.html",{"title":"Bloodlust"},[":md"]],
  ["v-2e9fcd2b","/options/Addons/Mixed/Diseased.html",{"title":"Diseased"},[":md"]],
  ["v-0874a9ba","/options/Addons/Mixed/Ghoul.html",{"title":"Ghoul"},[":md"]],
  ["v-9f2d9bb4","/options/Addons/Mixed/Glow.html",{"title":"Glow"},[":md"]],
  ["v-6cab0293","/options/Addons/Mixed/Gravestone.html",{"title":"Gravestone"},[":md"]],
  ["v-480c5cca","/options/Addons/Mixed/Guesser.html",{"title":"Guesser"},[":md"]],
  ["v-6256c6c8","/options/Addons/Mixed/Schizophrenic.html",{"title":"Schizophrenic"},[":md"]],
  ["v-7f5d8ffc","/options/Addons/Mixed/Stubborn.html",{"title":"Stubborn"},[":md"]],
  ["v-3ea83793","/options/Crewmates/Basic/Addict.html",{"title":"Addict"},[":md"]],
  ["v-5f22fab4","/options/Crewmates/Basic/Alchemist.html",{"title":"Alchemist"},[":md"]],
  ["v-69c26683","/options/Crewmates/Basic/Celebrity.html",{"title":"Celebrity"},[":md"]],
  ["v-b7417b16","/options/Crewmates/Basic/Cleanser.html",{"title":"Cleanser"},[":md"]],
  ["v-53707ee6","/options/Crewmates/Basic/Doctor.html",{"title":"Doctor"},[":md"]],
  ["v-7818fa22","/options/Crewmates/Basic/LazyGuy.html",{"title":"Lazy Guy"},[":md"]],
  ["v-e9a1f572","/options/Crewmates/Basic/Luckey.html",{"title":"Luckey"},[":md"]],
  ["v-99079dd6","/options/Crewmates/Basic/Mini.html",{"title":"Mini"},[":md"]],
  ["v-0270043e","/options/Crewmates/Basic/MiniEvil.html",{"title":"Evil Mini"},[":md"]],
  ["v-b52d6490","/options/Crewmates/Basic/MiniNice.html",{"title":"Nice Mini"},[":md"]],
  ["v-5c883a39","/options/Crewmates/Basic/SuperStar.html",{"title":"Super Star"},[":md"]],
  ["v-92d4cc44","/options/Crewmates/Basic/TaskManager.html",{"title":"Task Manager"},[":md"]],
  ["v-f805a70a","/options/Crewmates/Basic/Tracefinder.html",{"title":"Tracefinder"},[":md"]],
  ["v-edbca920","/options/Crewmates/Basic/Transporter.html",{"title":"Transporter"},[":md"]],
  ["v-172abac8","/options/Crewmates/Killing/Bastion.html",{"title":"Bastion"},[":md"]],
  ["v-769ed666","/options/Crewmates/Killing/Bodyguard.html",{"title":"Bodyguard"},[":md"]],
  ["v-1e341236","/options/Crewmates/Killing/Crusader.html",{"title":"Crusader"},[":md"]],
  ["v-d17913f6","/options/Crewmates/Killing/Deceiver.html",{"title":"Deceiver"},[":md"]],
  ["v-7a2efa05","/options/Crewmates/Killing/Jailor.html",{"title":"Jailor"},[":md"]],
  ["v-6c6e67f9","/options/Crewmates/Killing/Judge.html",{"title":"Judge"},[":md"]],
  ["v-00869d75","/options/Crewmates/Killing/Knight.html",{"title":"Knight"},[":md"]],
  ["v-fabb1fd2","/options/Crewmates/Killing/Retributionist.html",{"title":"Retributionist"},[":md"]],
  ["v-6cdb40c4","/options/Crewmates/Killing/Reverie.html",{"title":"Reverie"},[":md"]],
  ["v-3debb169","/options/Crewmates/Killing/Sheriff.html",{"title":"Sheriff"},[":md"]],
  ["v-0b38b791","/options/Crewmates/Killing/Veteran.html",{"title":"Veteran"},[":md"]],
  ["v-7dc3123b","/options/Crewmates/Killing/Vigilante.html",{"title":"Vigilante"},[":md"]],
  ["v-62dd8aa4","/options/Crewmates/Power/Copycat.html",{"title":"Copycat"},[":md"]],
  ["v-64642397","/options/Crewmates/Power/Dictator.html",{"title":"Dictator"},[":md"]],
  ["v-56cb219c","/options/Crewmates/Power/Guardian.html",{"title":"Guardian"},[":md"]],
  ["v-04534360","/options/Crewmates/Power/Lookout.html",{"title":"Lookout"},[":md"]],
  ["v-046fab56","/options/Crewmates/Power/Marshall.html",{"title":"Marshall"},[":md"]],
  ["v-80cd5272","/options/Crewmates/Power/Mayor.html",{"title":"Mayor"},[":md"]],
  ["v-8fef53a6","/options/Crewmates/Power/Monarch.html",{"title":"Monarch"},[":md"]],
  ["v-e23d9ea0","/options/Crewmates/Power/Overseer.html",{"title":"Overseer"},[":md"]],
  ["v-3c7311e3","/options/Crewmates/Power/Telecommunication.html",{"title":"Telecommunication"},[":md"]],
  ["v-9d586cf6","/options/Crewmates/Support/Admirer.html",{"title":"Admirer"},[":md"]],
  ["v-15ce620e","/options/Crewmates/Support/Chameleon.html",{"title":"Chameleon"},[":md"]],
  ["v-73e0429a","/options/Crewmates/Support/Coroner.html",{"title":"Coroner"},[":md"]],
  ["v-78e261fc","/options/Crewmates/Support/Deputy.html",{"title":"Deputy"},[":md"]],
  ["v-9b0700e0","/options/Crewmates/Support/Detective.html",{"title":"Detective"},[":md"]],
  ["v-72d5e55e","/options/Crewmates/Support/Engineer.html",{"title":"Engineer"},[":md"]],
  ["v-23d98766","/options/Crewmates/Support/FortuneTeller.html",{"title":"Fortune Teller"},[":md"]],
  ["v-b92bf0b4","/options/Crewmates/Support/Grenadier.html",{"title":"Grenadier"},[":md"]],
  ["v-0726852e","/options/Crewmates/Support/Inspector.html",{"title":"Inspector"},[":md"]],
  ["v-7032a662","/options/Crewmates/Support/Lighter.html",{"title":"Lighter"},[":md"]],
  ["v-33443969","/options/Crewmates/Support/Mechanic.html",{"title":"Mechanic"},[":md"]],
  ["v-a23538c2","/options/Crewmates/Support/Medic.html",{"title":"Medic"},[":md"]],
  ["v-4e41dd18","/options/Crewmates/Support/Medium.html",{"title":"Medium"},[":md"]],
  ["v-142cc9a5","/options/Crewmates/Support/Merchant.html",{"title":"Merchant"},[":md"]],
  ["v-38100ead","/options/Crewmates/Support/Mortician.html",{"title":"Mortician"},[":md"]],
  ["v-6f8e8d52","/options/Crewmates/Support/Observer.html",{"title":"Observer"},[":md"]],
  ["v-6c1a66a2","/options/Crewmates/Support/Oracle.html",{"title":"Oracle"},[":md"]],
  ["v-3f7db35c","/options/Crewmates/Support/Pacifist.html",{"title":"Pacifist"},[":md"]],
  ["v-f9a3bc60","/options/Crewmates/Support/Psychic.html",{"title":"Psychic"},[":md"]],
  ["v-923df8a6","/options/Crewmates/Support/Scientist.html",{"title":"Scientist"},[":md"]],
  ["v-05048abc","/options/Crewmates/Support/Snitch.html",{"title":"Snitch"},[":md"]],
  ["v-760420f2","/options/Crewmates/Support/Spiritualist.html",{"title":"Spiritualist"},[":md"]],
  ["v-78d782a5","/options/Crewmates/Support/TimeManager.html",{"title":"Time Manager"},[":md"]],
  ["v-8963b184","/options/Crewmates/Support/TimeMaster.html",{"title":"Time Master"},[":md"]],
  ["v-b85e96e6","/options/Crewmates/Support/Tracker.html",{"title":"Tracker"},[":md"]],
  ["v-76448f2c","/options/Crewmates/Support/Witness.html",{"title":"Witness"},[":md"]],
  ["v-9cdc7b8a","/options/Crewmates/Vanilla/CrewmateTOHE.html",{"title":"Crewmate"},[":md"]],
  ["v-3c5c945c","/options/Crewmates/Vanilla/EngineerTOHE.html",{"title":"Engineer"},[":md"]],
  ["v-9aecce6e","/options/Crewmates/Vanilla/ScientistTOHE.html",{"title":"Scientist"},[":md"]],
  ["v-3b655427","/options/Experimental/Addon/Fool.html",{"title":"Fool"},[":md"]],
  ["v-ef0c62c4","/options/Experimental/Addon/YouTuber.html",{"title":"YouTuber"},[":md"]],
  ["v-9173f078","/options/Experimental/Crewmate/Investigator.html",{"title":"Investigator"},[":md"]],
  ["v-5ca71efb","/options/Experimental/Crewmate/Swapper.html",{"title":"Swapper"},[":md"]],
  ["v-0d98c341","/options/Experimental/Impostor/Blackmailer.html",{"title":"Blackmailer"},[":md"]],
  ["v-4a0abb5e","/options/Experimental/Impostor/Butcher.html",{"title":"Butcher"},[":md"]],
  ["v-bcf1a81a","/options/Experimental/Impostor/Disperser.html",{"title":"Disperser"},[":md"]],
  ["v-348ffd02","/options/Experimental/Impostor/Eraser.html",{"title":"Eraser"},[":md"]],
  ["v-2b99319c","/options/Experimental/Impostor/Hangman.html",{"title":"Hangman"},[":md"]],
  ["v-7cd1590b","/options/Experimental/Impostor/KillingMachine.html",{"title":"Killing Machine"},[":md"]],
  ["v-66bf0cfa","/options/Experimental/Impostor/Lightning.html",{"title":"Lightning"},[":md"]],
  ["v-592179a8","/options/Experimental/Impostor/Zombie.html",{"title":"Zombie"},[":md"]],
  ["v-3a4e62d0","/options/Experimental/Neutral/Doppleganger.html",{"title":"Doppleganger"},[":md"]],
  ["v-6cfcbefc","/options/Experimental/Neutral/God.html",{"title":"God"},[":md"]],
  ["v-57b9c298","/options/Experimental/Neutral/Spiritcaller.html",{"title":"Spiritcaller"},[":md"]],
  ["v-2d9b93c4","/options/Impostors/Concealing/Escapist.html",{"title":"Escapist"},[":md"]],
  ["v-7cc822ee","/options/Impostors/Concealing/Miner.html",{"title":"Miner"},[":md"]],
  ["v-84c3586c","/options/Impostors/Concealing/Puppeteer.html",{"title":"Puppeteer"},[":md"]],
  ["v-03c7097c","/options/Impostors/Concealing/Scavenger.html",{"title":"Scavenger"},[":md"]],
  ["v-1aaf5b05","/options/Impostors/Concealing/Shapemaster.html",{"title":"Shapemaster"},[":md"]],
  ["v-a7447008","/options/Impostors/Concealing/Shapeshifter.html",{"title":"Shapeshifter"},[":md"]],
  ["v-7944ec53","/options/Impostors/Concealing/SoulCatcher.html",{"title":"Soul Catcher"},[":md"]],
  ["v-76e42e2f","/options/Impostors/Concealing/Swooper.html",{"title":"Swooper"},[":md"]],
  ["v-208cb3b2","/options/Impostors/Concealing/Trickster.html",{"title":"Trickster"},[":md"]],
  ["v-76928c57","/options/Impostors/Concealing/Undertaker.html",{"title":"Undertaker"},[":md"]],
  ["v-305d169a","/options/Impostors/Concealing/Vampire.html",{"title":"Vampire"},[":md"]],
  ["v-0c72ddb5","/options/Impostors/Concealing/Warlock.html",{"title":"Warlock"},[":md"]],
  ["v-4f084aea","/options/Impostors/Concealing/Wildling.html",{"title":"Wildling"},[":md"]],
  ["v-3dd0382c","/options/Impostors/Hindering/Anonymous.html",{"title":"Anonymous"},[":md"]],
  ["v-8af6768a","/options/Impostors/Hindering/Dazzler.html",{"title":"Dazzler"},[":md"]],
  ["v-2018ca37","/options/Impostors/Hindering/Devourer.html",{"title":"Devourer"},[":md"]],
  ["v-604e65e1","/options/Impostors/Hindering/Pitfall.html",{"title":"Pitfall"},[":md"]],
  ["v-0cdf5bba","/options/Impostors/Hindering/Twister.html",{"title":"Twister"},[":md"]],
  ["v-d83531e8","/options/Impostors/Killing/Agent.html",{"title":"Agent"},[":md"]],
  ["v-09d921ae","/options/Impostors/Killing/Arrogance.html",{"title":"Arrogance"},[":md"]],
  ["v-fee92548","/options/Impostors/Killing/Assassin.html",{"title":"Assassin"},[":md"]],
  ["v-4c2d1c0a","/options/Impostors/Killing/Berserker.html",{"title":"Berserker"},[":md"]],
  ["v-3ae27852","/options/Impostors/Killing/Bomber.html",{"title":"Bomber"},[":md"]],
  ["v-99ac82d4","/options/Impostors/Killing/BountyHunter.html",{"title":"Bounty Hunter"},[":md"]],
  ["v-527c7e48","/options/Impostors/Killing/Chronomancer.html",{"title":"Chronomancer"},[":md"]],
  ["v-ef8a051a","/options/Impostors/Killing/Councillor.html",{"title":"Councillor"},[":md"]],
  ["v-24debe86","/options/Impostors/Killing/CursedWolf.html",{"title":"Cursed Wolf"},[":md"]],
  ["v-6126561b","/options/Impostors/Killing/Deathpact.html",{"title":"Deathpact"},[":md"]],
  ["v-6cc20921","/options/Impostors/Killing/Greedy.html",{"title":"Greedy"},[":md"]],
  ["v-629e12a7","/options/Impostors/Killing/Inhibitor.html",{"title":"Inhibitor"},[":md"]],
  ["v-b99a8d30","/options/Impostors/Killing/Ludopath.html",{"title":"Ludopath"},[":md"]],
  ["v-51cad972","/options/Impostors/Killing/Lurker.html",{"title":"Lurker"},[":md"]],
  ["v-0e2f0bbb","/options/Impostors/Killing/Mercenary.html",{"title":"Mercenary"},[":md"]],
  ["v-51e2d2b2","/options/Impostors/Killing/Ninja.html",{"title":"Ninja"},[":md"]],
  ["v-883eae7c","/options/Impostors/Killing/QuickShooter.html",{"title":"Quick Shooter"},[":md"]],
  ["v-c8aa9210","/options/Impostors/Killing/Saboteur.html",{"title":"Saboteur"},[":md"]],
  ["v-f1f0c39c","/options/Impostors/Killing/Sniper.html",{"title":"Sniper"},[":md"]],
  ["v-165cda1d","/options/Impostors/Killing/Spellcaster.html",{"title":"Spellcaster"},[":md"]],
  ["v-c03015b4","/options/Impostors/Killing/Trapster.html",{"title":"Trapster"},[":md"]],
  ["v-c9e73246","/options/Impostors/Killing/Underdog.html",{"title":"Underdog"},[":md"]],
  ["v-de1610a4","/options/Impostors/Madmate/Crewpostor.html",{"title":"Crewpostor"},[":md"]],
  ["v-7349b86a","/options/Impostors/Madmate/Parasite.html",{"title":"Parasite"},[":md"]],
  ["v-ab2f7c90","/options/Impostors/Support/Camouflager.html",{"title":"Camouflager"},[":md"]],
  ["v-09fa1060","/options/Impostors/Support/Cleaner.html",{"title":"Cleaner"},[":md"]],
  ["v-5673f08c","/options/Impostors/Support/Consigliere.html",{"title":"Consigliere"},[":md"]],
  ["v-03be14ce","/options/Impostors/Support/Disruptor.html",{"title":"Disruptor"},[":md"]],
  ["v-03c72b18","/options/Impostors/Support/Fireworker.html",{"title":"Fireworker"},[":md"]],
  ["v-7d3297cb","/options/Impostors/Support/Gangster.html",{"title":"Gangster"},[":md"]],
  ["v-1e1101ae","/options/Impostors/Support/Godfather.html",{"title":"Godfather"},[":md"]],
  ["v-3a075570","/options/Impostors/Support/Morphling.html",{"title":"Morphling"},[":md"]],
  ["v-0d751a98","/options/Impostors/Support/Nemesis.html",{"title":"Nemesis"},[":md"]],
  ["v-afd96fc6","/options/Impostors/Support/TimeThief.html",{"title":"Time Thief"},[":md"]],
  ["v-272a8113","/options/Impostors/Support/Vindicator.html",{"title":"Vindicator"},[":md"]],
  ["v-880e83f4","/options/Impostors/Support/Visionary.html",{"title":"Visionary"},[":md"]],
  ["v-0f78ad8e","/options/Impostors/Vanilla/ImpostorTOHE.html",{"title":"Impostor"},[":md"]],
  ["v-c6084f5c","/options/Impostors/Vanilla/ShapeshifterTOHE.html",{"title":"Shapeshifter"},[":md"]],
  ["v-645bd8ed","/options/Neutrals/Benign/Amnesiac.html",{"title":"Amnesiac"},[":md"]],
  ["v-2a1165ec","/options/Neutrals/Benign/Follower.html",{"title":"Follower"},[":md"]],
  ["v-1521aa22","/options/Neutrals/Benign/Hater.html",{"title":"Hater"},[":md"]],
  ["v-48573e63","/options/Neutrals/Benign/Imitator.html",{"title":"Imitator"},[":md"]],
  ["v-7e2d0ea4","/options/Neutrals/Benign/Lawyer.html",{"title":"Lawyer"},[":md"]],
  ["v-7efe6df4","/options/Neutrals/Benign/Maverick.html",{"title":"Maverick"},[":md"]],
  ["v-5ae8c79b","/options/Neutrals/Benign/Opportunist.html",{"title":"Opportunist"},[":md"]],
  ["v-08442bce","/options/Neutrals/Benign/Pursuer.html",{"title":"Pursuer"},[":md"]],
  ["v-1cf0b797","/options/Neutrals/Benign/Romantic.html",{"title":"Romantic"},[":md"]],
  ["v-3be42d67","/options/Neutrals/Benign/RomanticRuthless.html",{"title":"Ruthless Romantic"},[":md"]],
  ["v-7de60452","/options/Neutrals/Benign/RomanticVengeful.html",{"title":"Vengeful Romantic"},[":md"]],
  ["v-70d7d48c","/options/Neutrals/Benign/Shaman.html",{"title":"Shaman"},[":md"]],
  ["v-e694537a","/options/Neutrals/Benign/Witch.html",{"title":"Witch"},[":md"]],
  ["v-d93ecad8","/options/Neutrals/Chaos/Collector.html",{"title":"Collector"},[":md"]],
  ["v-5e69da31","/options/Neutrals/Chaos/Cultist.html",{"title":"Cultist"},[":md"]],
  ["v-5d9c6bd8","/options/Neutrals/Chaos/Phantom.html",{"title":"Phantom"},[":md"]],
  ["v-37db9610","/options/Neutrals/Chaos/Pirate.html",{"title":"Pirate"},[":md"]],
  ["v-39c8b86f","/options/Neutrals/Chaos/Provocateur.html",{"title":"Provocateur"},[":md"]],
  ["v-f493d200","/options/Neutrals/Chaos/Revolutionist.html",{"title":"Revolutionist"},[":md"]],
  ["v-15a9b932","/options/Neutrals/Chaos/SoulCollector.html",{"title":"Soul Collector"},[":md"]],
  ["v-ee8d2a6a","/options/Neutrals/Chaos/Terrorist.html",{"title":"Terrorist"},[":md"]],
  ["v-b8a76764","/options/Neutrals/Chaos/Vector.html",{"title":"Vector"},[":md"]],
  ["v-feaf63c0","/options/Neutrals/Chaos/Vulture.html",{"title":"Vulture"},[":md"]],
  ["v-3d3c5662","/options/Neutrals/Chaos/Workaholic.html",{"title":"Workaholic"},[":md"]],
  ["v-22d8cc5c","/options/Neutrals/Evil/CursedSoul.html",{"title":"Cursed Soul"},[":md"]],
  ["v-2ddaa4a8","/options/Neutrals/Evil/Doomsayer.html",{"title":"Doomsayer"},[":md"]],
  ["v-433634f6","/options/Neutrals/Evil/Executioner.html",{"title":"Executioner"},[":md"]],
  ["v-1f1c89c9","/options/Neutrals/Evil/Innocent.html",{"title":"Innocent"},[":md"]],
  ["v-3e032824","/options/Neutrals/Evil/Jester.html",{"title":"Jester"},[":md"]],
  ["v-4a7a7c26","/options/Neutrals/Evil/Masochist.html",{"title":"Masochist"},[":md"]],
  ["v-5a600ed2","/options/Neutrals/Evil/Seeker.html",{"title":"Seeker"},[":md"]],
  ["v-63cf08ee","/options/Neutrals/Killing/Agitator.html",{"title":"Agitator"},[":md"]],
  ["v-a87f84a8","/options/Neutrals/Killing/Arsonist.html",{"title":"Arsonist"},[":md"]],
  ["v-64ad4a15","/options/Neutrals/Killing/Bandit.html",{"title":"Bandit"},[":md"]],
  ["v-50ccce36","/options/Neutrals/Killing/BloodKnight.html",{"title":"Blood Knight"},[":md"]],
  ["v-c8e29c1c","/options/Neutrals/Killing/Demon.html",{"title":"Demon"},[":md"]],
  ["v-1329bc20","/options/Neutrals/Killing/Glitch.html",{"title":"Glitch"},[":md"]],
  ["v-5ef14cc0","/options/Neutrals/Killing/HexMaster.html",{"title":"Hex Master"},[":md"]],
  ["v-3060994a","/options/Neutrals/Killing/Huntsman.html",{"title":"Huntsman"},[":md"]],
  ["v-c70ddc08","/options/Neutrals/Killing/Infectious.html",{"title":"Infectious"},[":md"]],
  ["v-619c93aa","/options/Neutrals/Killing/Jackal.html",{"title":"Jackal"},[":md"]],
  ["v-14a7d58c","/options/Neutrals/Killing/Jinx.html",{"title":"Jinx"},[":md"]],
  ["v-c98738ea","/options/Neutrals/Killing/Juggernaut.html",{"title":"Juggernaut"},[":md"]],
  ["v-b0fec344","/options/Neutrals/Killing/Medusa.html",{"title":"Medusa"},[":md"]],
  ["v-0a79c8c4","/options/Neutrals/Killing/Necromancer.html",{"title":"Necromancer"},[":md"]],
  ["v-543525fe","/options/Neutrals/Killing/Occultist.html",{"title":"Occultist"},[":md"]],
  ["v-0aa9c142","/options/Neutrals/Killing/Pelican.html",{"title":"Pelican"},[":md"]],
  ["v-6f248b9e","/options/Neutrals/Killing/Pickpocket.html",{"title":"Pickpocket"},[":md"]],
  ["v-0ee0bffc","/options/Neutrals/Killing/Plaguebearer.html",{"title":"Plaguebearer"},[":md"]],
  ["v-4238d8a0","/options/Neutrals/Killing/Poisoner.html",{"title":"Poisoner"},[":md"]],
  ["v-21bfdb00","/options/Neutrals/Killing/PotionMaster.html",{"title":"Potion Master"},[":md"]],
  ["v-2955f05e","/options/Neutrals/Killing/Pyromaniac.html",{"title":"Pyromaniac"},[":md"]],
  ["v-6ec03af6","/options/Neutrals/Killing/SerialKiller.html",{"title":"Serial Killer"},[":md"]],
  ["v-74db5bf0","/options/Neutrals/Killing/Shade.html",{"title":"Shade"},[":md"]],
  ["v-1d1b2774","/options/Neutrals/Killing/Shroud.html",{"title":"Shroud"},[":md"]],
  ["v-2241aff1","/options/Neutrals/Killing/Stalker.html",{"title":"Stalker"},[":md"]],
  ["v-0974f1a8","/options/Neutrals/Killing/Traitor.html",{"title":"Traitor"},[":md"]],
  ["v-671de120","/options/Neutrals/Killing/Virus.html",{"title":"Virus"},[":md"]],
  ["v-7a8c747c","/options/Neutrals/Killing/Werewolf.html",{"title":"Werewolf"},[":md"]],
  ["v-f4b1cec4","/options/Neutrals/Killing/Wraith.html",{"title":"Wraith"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
