export const pagesRoutes = [
  ["v-2ff80a47","/AboutUs.html",{"title":"About Us"},[":md"]],
  ["v-f8039104","/Advanced.html",{"title":"Advanced"},[":md"]],
  ["v-8667d2be","/Changelogs.html",{"title":"Changelogs"},[":md"]],
  ["v-39a2059c","/FAQ.html",{"title":"Frequently Asked Questions"},[":md"]],
  ["v-1eb00f35","/GetStarted.html",{"title":"Installation"},[":md"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/README.md"]],
  ["v-5bd8e7d6","/Roles.html",{"title":"Roles"},[":md"]],
  ["v-08078556","/vote.html",{"title":"Vote for E.N."},[":md"]],
  ["v-3934aeac","/changelogs/Canary.html",{"title":"Canary Changelogs"},[":md"]],
  ["v-5639b11b","/changelogs/Dev.html",{"title":"Dev Changelogs"},[":md"]],
  ["v-57f51832","/changelogs/Stable.html",{"title":"Stable Changelogs"},[":md"]],
  ["v-6ec8ec09","/changelogs/Tags.html",{"title":"Changelogs Tags"},[":md"]],
  ["v-3986a3e8","/zh-CN/AboutUs.html",{"title":"关于我们"},[":md"]],
  ["v-394e0c59","/zh-CN/Advanced.html",{"title":"Advanced"},[":md"]],
  ["v-5d7a20bc","/zh-CN/Changelogs.html",{"title":"Changelogs"},[":md"]],
  ["v-1d7153e1","/zh-CN/FAQ.html",{"title":"Frequently Asked Questions"},[":md"]],
  ["v-8143cd60","/zh-CN/GetStarted.html",{"title":"Installation"},[":md"]],
  ["v-016f45cc","/zh-CN/Roles.html",{"title":"Roles"},[":md"]],
  ["v-0bfd6e38","/options/Settings/Addons.html",{"title":"Add-ons"},[":md"]],
  ["v-3bd8288e","/options/Settings/Crewmates.html",{"title":"Crewmates"},[":md"]],
  ["v-3ebcba66","/options/Settings/Custom.html",{"title":"Custom Settings"},[":md"]],
  ["v-404e0662","/options/Settings/Experimental.html",{"title":"Experimental"},[":md"]],
  ["v-eab3bbf6","/options/Settings/Game.html",{"title":"Game Settings"},[":md"]],
  ["v-21df66e2","/options/Settings/Impostors.html",{"title":"Impostors"},[":md"]],
  ["v-b7336a82","/options/Settings/Modifiers.html",{"title":"Game Modifiers"},[":md"]],
  ["v-2db263ab","/options/Settings/Neutrals.html",{"title":"Neutrals"},[":md"]],
  ["v-4d2f5a68","/options/Settings/System.html",{"title":"System Settings"},[":md"]],
  ["v-f90fcba2","/zh-CN/changelogs/Canary.html",{"title":"Canary Changelogs"},[":md"]],
  ["v-7e4f35b6","/zh-CN/changelogs/Dev.html",{"title":"Dev Changelogs"},[":md"]],
  ["v-7417e56c","/zh-CN/changelogs/Stable.html",{"title":"Stable Changelogs"},[":md"]],
  ["v-4963face","/zh-CN/changelogs/Tags.html",{"title":"Changelogs Tags"},[":md"]],
  ["v-af508636","/options/Addons/Harmful/Disregarded.html",{"title":"Disregarded"},[":md"]],
  ["v-156447a1","/options/Addons/Harmful/Fragile.html",{"title":"Fragile"},[":md"]],
  ["v-07467b56","/options/Addons/Harmful/Hurried.html",{"title":"Hurried"},[":md"]],
  ["v-05db3c1c","/options/Addons/Harmful/Influenced.html",{"title":"Influenced"},[":md"]],
  ["v-40c332d2","/options/Addons/Harmful/Mundane.html",{"title":"Mundane"},[":md"]],
  ["v-48f47b27","/options/Addons/Harmful/Oblivious.html",{"title":"Oblivious"},[":md"]],
  ["v-511019b7","/options/Addons/Harmful/Rascal.html",{"title":"Rascal"},[":md"]],
  ["v-4e13bf82","/options/Addons/Harmful/Unlucky.html",{"title":"Unlucky"},[":md"]],
  ["v-2d08a8c9","/options/Addons/Harmful/VoidBallot.html",{"title":"Void Ballot"},[":md"]],
  ["v-6a019bf7","/options/Addons/Helpful/Autopsy.html",{"title":"Autopsy"},[":md"]],
  ["v-2afe320a","/options/Addons/Helpful/Bait.html",{"title":"Bait"},[":md"]],
  ["v-7a81cfb3","/options/Addons/Helpful/Beartrap.html",{"title":"Beartrap"},[":md"]],
  ["v-3622e43a","/options/Addons/Helpful/Bewilder.html",{"title":"Bewilder"},[":md"]],
  ["v-9f3cbb04","/options/Addons/Helpful/Burst.html",{"title":"Burst"},[":md"]],
  ["v-e0adda36","/options/Addons/Helpful/Cyber.html",{"title":"Cyber"},[":md"]],
  ["v-b78b24ae","/options/Addons/Helpful/DoubleShot.html",{"title":"Double Shot"},[":md"]],
  ["v-50b15dae","/options/Addons/Helpful/Flash.html",{"title":"Flash"},[":md"]],
  ["v-fd069b00","/options/Addons/Helpful/Lazy.html",{"title":"Lazy"},[":md"]],
  ["v-5a128386","/options/Addons/Helpful/Loyal.html",{"title":"Loyal"},[":md"]],
  ["v-f3366494","/options/Addons/Helpful/Lucky.html",{"title":"Lucky"},[":md"]],
  ["v-79a35ef0","/options/Addons/Helpful/Necroview.html",{"title":"Necroview"},[":md"]],
  ["v-697cc36a","/options/Addons/Helpful/Nimble.html",{"title":"Nimble"},[":md"]],
  ["v-134ca5a5","/options/Addons/Helpful/Overclocked.html",{"title":"Overclocked"},[":md"]],
  ["v-33b5d291","/options/Addons/Helpful/Repairman.html",{"title":"Repairman"},[":md"]],
  ["v-67e8b356","/options/Addons/Helpful/Seer.html",{"title":"Seer"},[":md"]],
  ["v-4b054902","/options/Addons/Helpful/Silent.html",{"title":"Silent"},[":md"]],
  ["v-5078afd7","/options/Addons/Helpful/Sleuth.html",{"title":"Sleuth"},[":md"]],
  ["v-6a389150","/options/Addons/Helpful/Tiebreaker.html",{"title":"Tiebreaker"},[":md"]],
  ["v-01132122","/options/Addons/Helpful/Torch.html",{"title":"Torch"},[":md"]],
  ["v-4ea01622","/options/Addons/Helpful/Watcher.html",{"title":"Watcher"},[":md"]],
  ["v-1940aa7f","/options/Addons/Impostor/Circumvent.html",{"title":"Circumvent"},[":md"]],
  ["v-a4efd4c8","/options/Addons/Impostor/Clumsy.html",{"title":"Clumsy"},[":md"]],
  ["v-5ebbf566","/options/Addons/Impostor/LastImpostor.html",{"title":"Last Impostor"},[":md"]],
  ["v-93f320cc","/options/Addons/Impostor/Madmate.html",{"title":"Madmate"},[":md"]],
  ["v-3ec6cc3c","/options/Addons/Impostor/Mare.html",{"title":"Mare"},[":md"]],
  ["v-5fa36c04","/options/Addons/Impostor/Mimic.html",{"title":"Mimic"},[":md"]],
  ["v-659c4613","/options/Addons/Impostor/Stealer.html",{"title":"Stealer"},[":md"]],
  ["v-13e5221c","/options/Addons/Impostor/Swift.html",{"title":"Swift"},[":md"]],
  ["v-27dfbf49","/options/Addons/Miscellaneous/Egoist.html",{"title":"Egoist"},[":md"]],
  ["v-142b6d33","/options/Addons/Miscellaneous/Lovers.html",{"title":"Lovers"},[":md"]],
  ["v-5a35700e","/options/Addons/Miscellaneous/Reach.html",{"title":"Reach"},[":md"]],
  ["v-2169ac20","/options/Addons/Miscellaneous/Workhorse.html",{"title":"Workhorse"},[":md"]],
  ["v-281456b5","/options/Addons/Mixed/Antidote.html",{"title":"Antidote"},[":md"]],
  ["v-7ed05ea9","/options/Addons/Mixed/Avenger.html",{"title":"Avenger"},[":md"]],
  ["v-b46d1c7e","/options/Addons/Mixed/Aware.html",{"title":"Aware"},[":md"]],
  ["v-3a19de3b","/options/Addons/Mixed/Bloodlust.html",{"title":"Bloodlust"},[":md"]],
  ["v-2e9fcd2b","/options/Addons/Mixed/Diseased.html",{"title":"Diseased"},[":md"]],
  ["v-0874a9ba","/options/Addons/Mixed/Ghoul.html",{"title":"Ghoul"},[":md"]],
  ["v-6cab0293","/options/Addons/Mixed/Gravestone.html",{"title":"Gravestone"},[":md"]],
  ["v-480c5cca","/options/Addons/Mixed/Guesser.html",{"title":"Guesser"},[":md"]],
  ["v-48594794","/options/Addons/Mixed/Rebound.html",{"title":"Rebound"},[":md"]],
  ["v-6256c6c8","/options/Addons/Mixed/Schizophrenic.html",{"title":"Schizophrenic"},[":md"]],
  ["v-7f5d8ffc","/options/Addons/Mixed/Stubborn.html",{"title":"Stubborn"},[":md"]],
  ["v-3ea83793","/options/Crewmates/Basic/Addict.html",{"title":"Addict"},[":md"]],
  ["v-5f22fab4","/options/Crewmates/Basic/Alchemist.html",{"title":"Alchemist"},[":md"]],
  ["v-69c26683","/options/Crewmates/Basic/Celebrity.html",{"title":"Celebrity"},[":md"]],
  ["v-b7417b16","/options/Crewmates/Basic/Cleanser.html",{"title":"Cleanser"},[":md"]],
  ["v-53707ee6","/options/Crewmates/Basic/Doctor.html",{"title":"Doctor"},[":md"]],
  ["v-2f4dbbcd","/options/Crewmates/Basic/GuessMaster.html",{"title":"Guess Master"},[":md"]],
  ["v-7818fa22","/options/Crewmates/Basic/LazyGuy.html",{"title":"Lazy Guy"},[":md"]],
  ["v-e9a1f572","/options/Crewmates/Basic/Luckey.html",{"title":"Luckey"},[":md"]],
  ["v-99079dd6","/options/Crewmates/Basic/Mini.html",{"title":"Mini"},[":md"]],
  ["v-0270043e","/options/Crewmates/Basic/MiniEvil.html",{"title":"Evil Mini"},[":md"]],
  ["v-b52d6490","/options/Crewmates/Basic/MiniNice.html",{"title":"Nice Mini"},[":md"]],
  ["v-9bb9355e","/options/Crewmates/Basic/Mole.html",{"title":"Mole"},[":md"]],
  ["v-2ee3e6ea","/options/Crewmates/Basic/Randomizer.html",{"title":"Randomizer"},[":md"]],
  ["v-5c883a39","/options/Crewmates/Basic/SuperStar.html",{"title":"Super Star"},[":md"]],
  ["v-92d4cc44","/options/Crewmates/Basic/TaskManager.html",{"title":"Task Manager"},[":md"]],
  ["v-f805a70a","/options/Crewmates/Basic/Tracefinder.html",{"title":"Tracefinder"},[":md"]],
  ["v-edbca920","/options/Crewmates/Basic/Transporter.html",{"title":"Transporter"},[":md"]],
  ["v-172abac8","/options/Crewmates/Killing/Bastion.html",{"title":"Bastion"},[":md"]],
  ["v-769ed666","/options/Crewmates/Killing/Bodyguard.html",{"title":"Bodyguard"},[":md"]],
  ["v-1e341236","/options/Crewmates/Killing/Crusader.html",{"title":"Crusader"},[":md"]],
  ["v-d17913f6","/options/Crewmates/Killing/Deceiver.html",{"title":"Deceiver"},[":md"]],
  ["v-6930a97b","/options/Crewmates/Killing/Jailer.html",{"title":"Jailer"},[":md"]],
  ["v-6c6e67f9","/options/Crewmates/Killing/Judge.html",{"title":"Judge"},[":md"]],
  ["v-00869d75","/options/Crewmates/Killing/Knight.html",{"title":"Knight"},[":md"]],
  ["v-3e880529","/options/Crewmates/Killing/NiceGuesser.html",{"title":"Nice Guesser"},[":md"]],
  ["v-fabb1fd2","/options/Crewmates/Killing/Retributionist.html",{"title":"Retributionist"},[":md"]],
  ["v-6cdb40c4","/options/Crewmates/Killing/Reverie.html",{"title":"Reverie"},[":md"]],
  ["v-3debb169","/options/Crewmates/Killing/Sheriff.html",{"title":"Sheriff"},[":md"]],
  ["v-0b38b791","/options/Crewmates/Killing/Veteran.html",{"title":"Veteran"},[":md"]],
  ["v-a53b7bca","/options/Crewmates/Killing/VIgilante.html",{"title":"Vigilante"},[":md"]],
  ["v-dc2894aa","/options/Crewmates/Power/Captain.html",{"title":"Captain"},[":md"]],
  ["v-62dd8aa4","/options/Crewmates/Power/Copycat.html",{"title":"Copycat"},[":md"]],
  ["v-64642397","/options/Crewmates/Power/Dictator.html",{"title":"Dictator"},[":md"]],
  ["v-56cb219c","/options/Crewmates/Power/Guardian.html",{"title":"Guardian"},[":md"]],
  ["v-04534360","/options/Crewmates/Power/Lookout.html",{"title":"Lookout"},[":md"]],
  ["v-046fab56","/options/Crewmates/Power/Marshall.html",{"title":"Marshall"},[":md"]],
  ["v-80cd5272","/options/Crewmates/Power/Mayor.html",{"title":"Mayor"},[":md"]],
  ["v-8fef53a6","/options/Crewmates/Power/Monarch.html",{"title":"Monarch"},[":md"]],
  ["v-e23d9ea0","/options/Crewmates/Power/Overseer.html",{"title":"Overseer"},[":md"]],
  ["v-e907e1e2","/options/Crewmates/Power/President.html",{"title":"President"},[":md"]],
  ["v-fe8bbc36","/options/Crewmates/Power/Swapper.html",{"title":"Swapper"},[":md"]],
  ["v-3c7311e3","/options/Crewmates/Power/Telecommunication.html",{"title":"Telecommunication"},[":md"]],
  ["v-27f96404","/options/Crewmates/Support/Benefactor.html",{"title":"Benefactor"},[":md"]],
  ["v-15ce620e","/options/Crewmates/Support/Chameleon.html",{"title":"Chameleon"},[":md"]],
  ["v-73e0429a","/options/Crewmates/Support/Coroner.html",{"title":"Coroner"},[":md"]],
  ["v-78e261fc","/options/Crewmates/Support/Deputy.html",{"title":"Deputy"},[":md"]],
  ["v-9b0700e0","/options/Crewmates/Support/Detective.html",{"title":"Detective"},[":md"]],
  ["v-d0cdde1c","/options/Crewmates/Support/Enigma.html",{"title":"Enigma"},[":md"]],
  ["v-23d98766","/options/Crewmates/Support/FortuneTeller.html",{"title":"Fortune Teller"},[":md"]],
  ["v-b92bf0b4","/options/Crewmates/Support/Grenadier.html",{"title":"Grenadier"},[":md"]],
  ["v-0726852e","/options/Crewmates/Support/Inspector.html",{"title":"Inspector"},[":md"]],
  ["v-4a09a7bb","/options/Crewmates/Support/Keeper.html",{"title":"Keeper"},[":md"]],
  ["v-7032a662","/options/Crewmates/Support/Lighter.html",{"title":"Lighter"},[":md"]],
  ["v-33443969","/options/Crewmates/Support/Mechanic.html",{"title":"Mechanic"},[":md"]],
  ["v-a23538c2","/options/Crewmates/Support/Medic.html",{"title":"Medic"},[":md"]],
  ["v-4e41dd18","/options/Crewmates/Support/Medium.html",{"title":"Medium"},[":md"]],
  ["v-142cc9a5","/options/Crewmates/Support/Merchant.html",{"title":"Merchant"},[":md"]],
  ["v-38100ead","/options/Crewmates/Support/Mortician.html",{"title":"Mortician"},[":md"]],
  ["v-6f8e8d52","/options/Crewmates/Support/Observer.html",{"title":"Observer"},[":md"]],
  ["v-6c1a66a2","/options/Crewmates/Support/Oracle.html",{"title":"Oracle"},[":md"]],
  ["v-3f7db35c","/options/Crewmates/Support/Pacifist.html",{"title":"Pacifist"},[":md"]],
  ["v-f9a3bc60","/options/Crewmates/Support/Psychic.html",{"title":"Psychic"},[":md"]],
  ["v-05048abc","/options/Crewmates/Support/Snitch.html",{"title":"Snitch"},[":md"]],
  ["v-760420f2","/options/Crewmates/Support/Spiritualist.html",{"title":"Spiritualist"},[":md"]],
  ["v-ebefd2ee","/options/Crewmates/Support/Spy.html",{"title":"Spy"},[":md"]],
  ["v-78d782a5","/options/Crewmates/Support/TimeManager.html",{"title":"Time Manager"},[":md"]],
  ["v-8963b184","/options/Crewmates/Support/TimeMaster.html",{"title":"Time Master"},[":md"]],
  ["v-b85e96e6","/options/Crewmates/Support/Tracker.html",{"title":"Tracker"},[":md"]],
  ["v-76448f2c","/options/Crewmates/Support/Witness.html",{"title":"Witness"},[":md"]],
  ["v-3d0de61a","/options/Crewmates/Vanilla/Crewmate.html",{"title":"Crewmate"},[":md"]],
  ["v-c40f37ec","/options/Crewmates/Vanilla/Engineer.html",{"title":"Engineer"},[":md"]],
  ["v-1fe34afe","/options/Crewmates/Vanilla/Scientist.html",{"title":"Scientist"},[":md"]],
  ["v-3b655427","/options/Experimental/Addon/Fool.html",{"title":"Fool"},[":md"]],
  ["v-1e8b2c0e","/options/Experimental/Addon/OiiaiCat.html",{"title":"Oiiai Cat"},[":md"]],
  ["v-ef0c62c4","/options/Experimental/Addon/YouTuber.html",{"title":"YouTuber"},[":md"]],
  ["v-0af64fb6","/options/Experimental/Crewmate/Admirer.html",{"title":"Admirer"},[":md"]],
  ["v-9173f078","/options/Experimental/Crewmate/Investigator.html",{"title":"Investigator"},[":md"]],
  ["v-0d98c341","/options/Experimental/Impostor/Blackmailer.html",{"title":"Blackmailer"},[":md"]],
  ["v-4a0abb5e","/options/Experimental/Impostor/Butcher.html",{"title":"Butcher"},[":md"]],
  ["v-bcf1a81a","/options/Experimental/Impostor/Disperser.html",{"title":"Disperser"},[":md"]],
  ["v-348ffd02","/options/Experimental/Impostor/Eraser.html",{"title":"Eraser"},[":md"]],
  ["v-2b99319c","/options/Experimental/Impostor/Hangman.html",{"title":"Hangman"},[":md"]],
  ["v-7cd1590b","/options/Experimental/Impostor/KillingMachine.html",{"title":"Killing Machine"},[":md"]],
  ["v-66bf0cfa","/options/Experimental/Impostor/Lightning.html",{"title":"Lightning"},[":md"]],
  ["v-592179a8","/options/Experimental/Impostor/Zombie.html",{"title":"Zombie"},[":md"]],
  ["v-2ad68a3c","/options/Experimental/Neutral/Doppelganger.html",{"title":"Doppelganger"},[":md"]],
  ["v-6cfcbefc","/options/Experimental/Neutral/God.html",{"title":"God"},[":md"]],
  ["v-161537f4","/options/Experimental/Neutral/Solsticer.html",{"title":"Solsticer"},[":md"]],
  ["v-57b9c298","/options/Experimental/Neutral/Spiritcaller.html",{"title":"Spiritcaller"},[":md"]],
  ["v-2d9b93c4","/options/Impostors/Concealing/Escapist.html",{"title":"Escapist"},[":md"]],
  ["v-0c013036","/options/Impostors/Concealing/Mastermind.html",{"title":"Mastermind"},[":md"]],
  ["v-7cc822ee","/options/Impostors/Concealing/Miner.html",{"title":"Miner"},[":md"]],
  ["v-84c3586c","/options/Impostors/Concealing/Puppeteer.html",{"title":"Puppeteer"},[":md"]],
  ["v-03c7097c","/options/Impostors/Concealing/Scavenger.html",{"title":"Scavenger"},[":md"]],
  ["v-1aaf5b05","/options/Impostors/Concealing/Shapemaster.html",{"title":"Shapemaster"},[":md"]],
  ["v-7944ec53","/options/Impostors/Concealing/SoulCatcher.html",{"title":"Soul Catcher"},[":md"]],
  ["v-76e42e2f","/options/Impostors/Concealing/Swooper.html",{"title":"Swooper"},[":md"]],
  ["v-208cb3b2","/options/Impostors/Concealing/Trickster.html",{"title":"Trickster"},[":md"]],
  ["v-76928c57","/options/Impostors/Concealing/Undertaker.html",{"title":"Undertaker"},[":md"]],
  ["v-305d169a","/options/Impostors/Concealing/Vampire.html",{"title":"Vampire"},[":md"]],
  ["v-432ed00c","/options/Impostors/Concealing/Vampiress.html",{"title":"Vampiress"},[":md"]],
  ["v-0c72ddb5","/options/Impostors/Concealing/Warlock.html",{"title":"Warlock"},[":md"]],
  ["v-4f084aea","/options/Impostors/Concealing/Wildling.html",{"title":"Wildling"},[":md"]],
  ["v-3dd0382c","/options/Impostors/Hindering/Anonymous.html",{"title":"Anonymous"},[":md"]],
  ["v-8af6768a","/options/Impostors/Hindering/Dazzler.html",{"title":"Dazzler"},[":md"]],
  ["v-2018ca37","/options/Impostors/Hindering/Devourer.html",{"title":"Devourer"},[":md"]],
  ["v-604e65e1","/options/Impostors/Hindering/Pitfall.html",{"title":"Pitfall"},[":md"]],
  ["v-0cdf5bba","/options/Impostors/Hindering/Twister.html",{"title":"Twister"},[":md"]],
  ["v-09d921ae","/options/Impostors/Killing/Arrogance.html",{"title":"Arrogance"},[":md"]],
  ["v-873d60a0","/options/Impostors/Killing/Bard.html",{"title":"Bard"},[":md"]],
  ["v-4c2d1c0a","/options/Impostors/Killing/Berserker.html",{"title":"Berserker"},[":md"]],
  ["v-3ae27852","/options/Impostors/Killing/Bomber.html",{"title":"Bomber"},[":md"]],
  ["v-99ac82d4","/options/Impostors/Killing/BountyHunter.html",{"title":"Bounty Hunter"},[":md"]],
  ["v-527c7e48","/options/Impostors/Killing/Chronomancer.html",{"title":"Chronomancer"},[":md"]],
  ["v-ef8a051a","/options/Impostors/Killing/Councillor.html",{"title":"Councillor"},[":md"]],
  ["v-24debe86","/options/Impostors/Killing/CursedWolf.html",{"title":"Cursed Wolf"},[":md"]],
  ["v-6126561b","/options/Impostors/Killing/Deathpact.html",{"title":"Deathpact"},[":md"]],
  ["v-27aa9e61","/options/Impostors/Killing/EvilGuesser.html",{"title":"Evil Guesser"},[":md"]],
  ["v-788bd06d","/options/Impostors/Killing/EvilTracker.html",{"title":"Evil Tracker"},[":md"]],
  ["v-6cc20921","/options/Impostors/Killing/Greedy.html",{"title":"Greedy"},[":md"]],
  ["v-629e12a7","/options/Impostors/Killing/Inhibitor.html",{"title":"Inhibitor"},[":md"]],
  ["v-f0f11672","/options/Impostors/Killing/Instigator.html",{"title":"Instigator"},[":md"]],
  ["v-b99a8d30","/options/Impostors/Killing/Ludopath.html",{"title":"Ludopath"},[":md"]],
  ["v-51cad972","/options/Impostors/Killing/Lurker.html",{"title":"Lurker"},[":md"]],
  ["v-0e2f0bbb","/options/Impostors/Killing/Mercenary.html",{"title":"Mercenary"},[":md"]],
  ["v-51e2d2b2","/options/Impostors/Killing/Ninja.html",{"title":"Ninja"},[":md"]],
  ["v-b1b90340","/options/Impostors/Killing/Nuker.html",{"title":"Nuker"},[":md"]],
  ["v-883eae7c","/options/Impostors/Killing/QuickShooter.html",{"title":"Quick Shooter"},[":md"]],
  ["v-c8aa9210","/options/Impostors/Killing/Saboteur.html",{"title":"Saboteur"},[":md"]],
  ["v-f1f0c39c","/options/Impostors/Killing/Sniper.html",{"title":"Sniper"},[":md"]],
  ["v-165cda1d","/options/Impostors/Killing/Spellcaster.html",{"title":"Spellcaster"},[":md"]],
  ["v-c03015b4","/options/Impostors/Killing/Trapster.html",{"title":"Trapster"},[":md"]],
  ["v-c9e73246","/options/Impostors/Killing/Underdog.html",{"title":"Underdog"},[":md"]],
  ["v-de1610a4","/options/Impostors/Madmate/Crewpostor.html",{"title":"Crewpostor"},[":md"]],
  ["v-7349b86a","/options/Impostors/Madmate/Parasite.html",{"title":"Parasite"},[":md"]],
  ["v-7dc523e8","/options/Impostors/Support/AntiAdminer.html",{"title":"Anti Adminer"},[":md"]],
  ["v-ab2f7c90","/options/Impostors/Support/Camouflager.html",{"title":"Camouflager"},[":md"]],
  ["v-09fa1060","/options/Impostors/Support/Cleaner.html",{"title":"Cleaner"},[":md"]],
  ["v-5673f08c","/options/Impostors/Support/Consigliere.html",{"title":"Consigliere"},[":md"]],
  ["v-03c72b18","/options/Impostors/Support/Fireworker.html",{"title":"Fireworker"},[":md"]],
  ["v-7d3297cb","/options/Impostors/Support/Gangster.html",{"title":"Gangster"},[":md"]],
  ["v-1e1101ae","/options/Impostors/Support/Godfather.html",{"title":"Godfather"},[":md"]],
  ["v-73c6f0f9","/options/Impostors/Support/Kamikaze.html",{"title":"Kamikaze"},[":md"]],
  ["v-3a075570","/options/Impostors/Support/Morphling.html",{"title":"Morphling"},[":md"]],
  ["v-0d751a98","/options/Impostors/Support/Nemesis.html",{"title":"Nemesis"},[":md"]],
  ["v-afd96fc6","/options/Impostors/Support/TimeThief.html",{"title":"Time Thief"},[":md"]],
  ["v-272a8113","/options/Impostors/Support/Vindicator.html",{"title":"Vindicator"},[":md"]],
  ["v-880e83f4","/options/Impostors/Support/Visionary.html",{"title":"Visionary"},[":md"]],
  ["v-827bba1e","/options/Impostors/Vanilla/Impostor.html",{"title":"Impostor"},[":md"]],
  ["v-5497c68a","/options/Impostors/Vanilla/Shapeshifter.html",{"title":"Shapeshifter"},[":md"]],
  ["v-645bd8ed","/options/Neutrals/Benign/Amnesiac.html",{"title":"Amnesiac"},[":md"]],
  ["v-2a1165ec","/options/Neutrals/Benign/Follower.html",{"title":"Follower"},[":md"]],
  ["v-1521aa22","/options/Neutrals/Benign/Hater.html",{"title":"Hater"},[":md"]],
  ["v-48573e63","/options/Neutrals/Benign/Imitator.html",{"title":"Imitator"},[":md"]],
  ["v-7e2d0ea4","/options/Neutrals/Benign/Lawyer.html",{"title":"Lawyer"},[":md"]],
  ["v-7efe6df4","/options/Neutrals/Benign/Maverick.html",{"title":"Maverick"},[":md"]],
  ["v-5ae8c79b","/options/Neutrals/Benign/Opportunist.html",{"title":"Opportunist"},[":md"]],
  ["v-930168e2","/options/Neutrals/Benign/Pixie.html",{"title":"Pixie"},[":md"]],
  ["v-08442bce","/options/Neutrals/Benign/Pursuer.html",{"title":"Pursuer"},[":md"]],
  ["v-1cf0b797","/options/Neutrals/Benign/Romantic.html",{"title":"Romantic"},[":md"]],
  ["v-3be42d67","/options/Neutrals/Benign/RomanticRuthless.html",{"title":"Ruthless Romantic"},[":md"]],
  ["v-7de60452","/options/Neutrals/Benign/RomanticVengeful.html",{"title":"Vengeful Romantic"},[":md"]],
  ["v-70d7d48c","/options/Neutrals/Benign/Shaman.html",{"title":"Shaman"},[":md"]],
  ["v-02fa1e30","/options/Neutrals/Benign/Taskinator.html",{"title":"Taskinator"},[":md"]],
  ["v-e694537a","/options/Neutrals/Benign/Witch.html",{"title":"Witch"},[":md"]],
  ["v-d93ecad8","/options/Neutrals/Chaos/Collector.html",{"title":"Collector"},[":md"]],
  ["v-5e69da31","/options/Neutrals/Chaos/Cultist.html",{"title":"Cultist"},[":md"]],
  ["v-5d9c6bd8","/options/Neutrals/Chaos/Phantom.html",{"title":"Phantom"},[":md"]],
  ["v-37db9610","/options/Neutrals/Chaos/Pirate.html",{"title":"Pirate"},[":md"]],
  ["v-39c8b86f","/options/Neutrals/Chaos/Provocateur.html",{"title":"Provocateur"},[":md"]],
  ["v-f493d200","/options/Neutrals/Chaos/Revolutionist.html",{"title":"Revolutionist"},[":md"]],
  ["v-15a9b932","/options/Neutrals/Chaos/SoulCollector.html",{"title":"Soul Collector"},[":md"]],
  ["v-ee8d2a6a","/options/Neutrals/Chaos/Terrorist.html",{"title":"Terrorist"},[":md"]],
  ["v-b8a76764","/options/Neutrals/Chaos/Vector.html",{"title":"Vector"},[":md"]],
  ["v-feaf63c0","/options/Neutrals/Chaos/Vulture.html",{"title":"Vulture"},[":md"]],
  ["v-3d3c5662","/options/Neutrals/Chaos/Workaholic.html",{"title":"Workaholic"},[":md"]],
  ["v-22d8cc5c","/options/Neutrals/Evil/CursedSoul.html",{"title":"Cursed Soul"},[":md"]],
  ["v-2ddaa4a8","/options/Neutrals/Evil/Doomsayer.html",{"title":"Doomsayer"},[":md"]],
  ["v-433634f6","/options/Neutrals/Evil/Executioner.html",{"title":"Executioner"},[":md"]],
  ["v-1f1c89c9","/options/Neutrals/Evil/Innocent.html",{"title":"Innocent"},[":md"]],
  ["v-3e032824","/options/Neutrals/Evil/Jester.html",{"title":"Jester"},[":md"]],
  ["v-4a7a7c26","/options/Neutrals/Evil/Masochist.html",{"title":"Masochist"},[":md"]],
  ["v-5a600ed2","/options/Neutrals/Evil/Seeker.html",{"title":"Seeker"},[":md"]],
  ["v-75795922","/options/Neutrals/Evil/Sunnyboy.html",{"title":"Sunnyboy"},[":md"]],
  ["v-63cf08ee","/options/Neutrals/Killing/Agitator.html",{"title":"Agitator"},[":md"]],
  ["v-a87f84a8","/options/Neutrals/Killing/Arsonist.html",{"title":"Arsonist"},[":md"]],
  ["v-64ad4a15","/options/Neutrals/Killing/Bandit.html",{"title":"Bandit"},[":md"]],
  ["v-50ccce36","/options/Neutrals/Killing/BloodKnight.html",{"title":"Blood Knight"},[":md"]],
  ["v-c8e29c1c","/options/Neutrals/Killing/Demon.html",{"title":"Demon"},[":md"]],
  ["v-1329bc20","/options/Neutrals/Killing/Glitch.html",{"title":"Glitch"},[":md"]],
  ["v-5ef14cc0","/options/Neutrals/Killing/HexMaster.html",{"title":"Hex Master"},[":md"]],
  ["v-3060994a","/options/Neutrals/Killing/Huntsman.html",{"title":"Huntsman"},[":md"]],
  ["v-c70ddc08","/options/Neutrals/Killing/Infectious.html",{"title":"Infectious"},[":md"]],
  ["v-619c93aa","/options/Neutrals/Killing/Jackal.html",{"title":"Jackal"},[":md"]],
  ["v-14a7d58c","/options/Neutrals/Killing/Jinx.html",{"title":"Jinx"},[":md"]],
  ["v-c98738ea","/options/Neutrals/Killing/Juggernaut.html",{"title":"Juggernaut"},[":md"]],
  ["v-b0fec344","/options/Neutrals/Killing/Medusa.html",{"title":"Medusa"},[":md"]],
  ["v-0a79c8c4","/options/Neutrals/Killing/Necromancer.html",{"title":"Necromancer"},[":md"]],
  ["v-543525fe","/options/Neutrals/Killing/Occultist.html",{"title":"Occultist"},[":md"]],
  ["v-0aa9c142","/options/Neutrals/Killing/Pelican.html",{"title":"Pelican"},[":md"]],
  ["v-6f248b9e","/options/Neutrals/Killing/Pickpocket.html",{"title":"Pickpocket"},[":md"]],
  ["v-0ee0bffc","/options/Neutrals/Killing/Plaguebearer.html",{"title":"Plaguebearer"},[":md"]],
  ["v-4238d8a0","/options/Neutrals/Killing/Poisoner.html",{"title":"Poisoner"},[":md"]],
  ["v-21bfdb00","/options/Neutrals/Killing/PotionMaster.html",{"title":"Potion Master"},[":md"]],
  ["v-2955f05e","/options/Neutrals/Killing/Pyromaniac.html",{"title":"Pyromaniac"},[":md"]],
  ["v-6ec03af6","/options/Neutrals/Killing/SerialKiller.html",{"title":"Serial Killer"},[":md"]],
  ["v-1d1b2774","/options/Neutrals/Killing/Shroud.html",{"title":"Shroud"},[":md"]],
  ["v-2241aff1","/options/Neutrals/Killing/Stalker.html",{"title":"Stalker"},[":md"]],
  ["v-0974f1a8","/options/Neutrals/Killing/Traitor.html",{"title":"Traitor"},[":md"]],
  ["v-671de120","/options/Neutrals/Killing/Virus.html",{"title":"Virus"},[":md"]],
  ["v-7a8c747c","/options/Neutrals/Killing/Werewolf.html",{"title":"Werewolf"},[":md"]],
  ["v-f4b1cec4","/options/Neutrals/Killing/Wraith.html",{"title":"Wraith"},[":md"]],
  ["v-3f507aae","/zh-CN/options/Settings/Addons.html",{"title":"Add-ons"},[":md"]],
  ["v-35c6c6ae","/zh-CN/options/Settings/Crewmates.html",{"title":"Crewmates"},[":md"]],
  ["v-2513342b","/zh-CN/options/Settings/Custom.html",{"title":"Custom Settings"},[":md"]],
  ["v-96476258","/zh-CN/options/Settings/Experimental.html",{"title":"Experimental"},[":md"]],
  ["v-116a490a","/zh-CN/options/Settings/Game.html",{"title":"Game Settings"},[":md"]],
  ["v-cf567eac","/zh-CN/options/Settings/Impostors.html",{"title":"Impostors"},[":md"]],
  ["v-4daabeda","/zh-CN/options/Settings/Modifiers.html",{"title":"Game Modifiers"},[":md"]],
  ["v-4f5cffa0","/zh-CN/options/Settings/Neutrals.html",{"title":"Neutrals"},[":md"]],
  ["v-3385d42d","/zh-CN/options/Settings/System.html",{"title":"System Settings"},[":md"]],
  ["v-731fe600","/zh-CN/options/Addons/Harmful/Disregarded.html",{"title":"Disregarded"},[":md"]],
  ["v-3e699388","/zh-CN/options/Addons/Harmful/Fragile.html",{"title":"Fragile"},[":md"]],
  ["v-5aa52c1e","/zh-CN/options/Addons/Harmful/Hurried.html",{"title":"Hurried"},[":md"]],
  ["v-1c632977","/zh-CN/options/Addons/Harmful/Influenced.html",{"title":"Influenced"},[":md"]],
  ["v-534ba1fc","/zh-CN/options/Addons/Harmful/Oblivious.html",{"title":"Oblivious"},[":md"]],
  ["v-26136bbc","/zh-CN/options/Addons/Harmful/Rascal.html",{"title":"Rascal"},[":md"]],
  ["v-197aae1d","/zh-CN/options/Addons/Harmful/Unlucky.html",{"title":"Unlucky"},[":md"]],
  ["v-4c59704e","/zh-CN/options/Addons/Harmful/VoidBallot.html",{"title":"Void Ballot"},[":md"]],
  ["v-37ee58cc","/zh-CN/options/Addons/Impostor/Circumvent.html",{"title":"Circumvent"},[":md"]],
  ["v-78ef0437","/zh-CN/options/Addons/Impostor/Clumsy.html",{"title":"Clumsy"},[":md"]],
  ["v-cfc3787e","/zh-CN/options/Addons/Impostor/LastImpostor.html",{"title":"Last Impostor"},[":md"]],
  ["v-577d545f","/zh-CN/options/Addons/Impostor/Madmate.html",{"title":"Madmate"},[":md"]],
  ["v-ae82b4d2","/zh-CN/options/Addons/Impostor/Mare.html",{"title":"Mare"},[":md"]],
  ["v-34a6be09","/zh-CN/options/Addons/Impostor/Mimic.html",{"title":"Mimic"},[":md"]],
  ["v-07132ad8","/zh-CN/options/Addons/Impostor/Stealer.html",{"title":"Stealer"},[":md"]],
  ["v-2e2f17be","/zh-CN/options/Addons/Impostor/Swift.html",{"title":"Swift"},[":md"]],
  ["v-35688a92","/zh-CN/options/Addons/Helpful/Autopsy.html",{"title":"Autopsy"},[":md"]],
  ["v-ab6f7d62","/zh-CN/options/Addons/Helpful/Bait.html",{"title":"Bait"},[":md"]],
  ["v-1bf8b478","/zh-CN/options/Addons/Helpful/Beartrap.html",{"title":"Beartrap"},[":md"]],
  ["v-50cc6e02","/zh-CN/options/Addons/Helpful/Bewilder.html",{"title":"Bewilder"},[":md"]],
  ["v-1a597bd9","/zh-CN/options/Addons/Helpful/Burst.html",{"title":"Burst"},[":md"]],
  ["v-0cbe2780","/zh-CN/options/Addons/Helpful/Cyber.html",{"title":"Cyber"},[":md"]],
  ["v-78e995a4","/zh-CN/options/Addons/Helpful/DoubleShot.html",{"title":"Double Shot"},[":md"]],
  ["v-00c6c1c5","/zh-CN/options/Addons/Helpful/Lazy.html",{"title":"Lazy"},[":md"]],
  ["v-3cee9798","/zh-CN/options/Addons/Helpful/Loyal.html",{"title":"Loyal"},[":md"]],
  ["v-1f46b1de","/zh-CN/options/Addons/Helpful/Lucky.html",{"title":"Lucky"},[":md"]],
  ["v-070912cb","/zh-CN/options/Addons/Helpful/Necroview.html",{"title":"Necroview"},[":md"]],
  ["v-bf761f60","/zh-CN/options/Addons/Helpful/Nimble.html",{"title":"Nimble"},[":md"]],
  ["v-43d66280","/zh-CN/options/Addons/Helpful/Overclocked.html",{"title":"Overclocked"},[":md"]],
  ["v-7dc8f328","/zh-CN/options/Addons/Helpful/Repairman.html",{"title":"Repairman"},[":md"]],
  ["v-4b55b59a","/zh-CN/options/Addons/Helpful/Seer.html",{"title":"Seer"},[":md"]],
  ["v-257c01dc","/zh-CN/options/Addons/Helpful/Sleuth.html",{"title":"Sleuth"},[":md"]],
  ["v-2b970246","/zh-CN/options/Addons/Helpful/Tiebreaker.html",{"title":"Tiebreaker"},[":md"]],
  ["v-6b0afa7d","/zh-CN/options/Addons/Helpful/Torch.html",{"title":"Torch"},[":md"]],
  ["v-1a0704bd","/zh-CN/options/Addons/Helpful/Watcher.html",{"title":"Watcher"},[":md"]],
  ["v-93c68ce4","/zh-CN/options/Addons/Miscellaneous/Egoist.html",{"title":"Egoist"},[":md"]],
  ["v-bb2f3110","/zh-CN/options/Addons/Miscellaneous/Lovers.html",{"title":"Lovers"},[":md"]],
  ["v-c4a51dd8","/zh-CN/options/Addons/Miscellaneous/Reach.html",{"title":"Reach"},[":md"]],
  ["v-e91c608a","/zh-CN/options/Addons/Miscellaneous/Workhorse.html",{"title":"Workhorse"},[":md"]],
  ["v-0a0f262e","/zh-CN/options/Crewmates/Basic/Addict.html",{"title":"Addict"},[":md"]],
  ["v-7e73c239","/zh-CN/options/Crewmates/Basic/Alchemist.html",{"title":"Alchemist"},[":md"]],
  ["v-edd9a3f0","/zh-CN/options/Crewmates/Basic/Celebrity.html",{"title":"Celebrity"},[":md"]],
  ["v-31c4f650","/zh-CN/options/Crewmates/Basic/Cleanser.html",{"title":"Cleanser"},[":md"]],
  ["v-bca2a1b0","/zh-CN/options/Crewmates/Basic/Doctor.html",{"title":"Doctor"},[":md"]],
  ["v-656a67b4","/zh-CN/options/Crewmates/Basic/LazyGuy.html",{"title":"Lazy Guy"},[":md"]],
  ["v-5695f3e2","/zh-CN/options/Crewmates/Basic/Luckey.html",{"title":"Luckey"},[":md"]],
  ["v-1d740a70","/zh-CN/options/Crewmates/Basic/Mini.html",{"title":"Mini"},[":md"]],
  ["v-e7a49c88","/zh-CN/options/Crewmates/Basic/MiniEvil.html",{"title":"Evil Mini"},[":md"]],
  ["v-32cf0193","/zh-CN/options/Crewmates/Basic/MiniNice.html",{"title":"Nice Mini"},[":md"]],
  ["v-995394b4","/zh-CN/options/Crewmates/Basic/Randomizer.html",{"title":"Randomizer"},[":md"]],
  ["v-7bd901be","/zh-CN/options/Crewmates/Basic/SuperStar.html",{"title":"Super Star"},[":md"]],
  ["v-44d29423","/zh-CN/options/Crewmates/Basic/TaskManager.html",{"title":"Task Manager"},[":md"]],
  ["v-123a26c0","/zh-CN/options/Crewmates/Basic/Tracefinder.html",{"title":"Tracefinder"},[":md"]],
  ["v-175ea5b5","/zh-CN/options/Crewmates/Basic/Transporter.html",{"title":"Transporter"},[":md"]],
  ["v-05d0ae8c","/zh-CN/options/Addons/Mixed/Antidote.html",{"title":"Antidote"},[":md"]],
  ["v-2e6f8ff8","/zh-CN/options/Addons/Mixed/Avenger.html",{"title":"Avenger"},[":md"]],
  ["v-4f0de5dc","/zh-CN/options/Addons/Mixed/Aware.html",{"title":"Aware"},[":md"]],
  ["v-0580ccd6","/zh-CN/options/Addons/Mixed/Bloodlust.html",{"title":"Bloodlust"},[":md"]],
  ["v-03a31f30","/zh-CN/options/Addons/Mixed/Diseased.html",{"title":"Diseased"},[":md"]],
  ["v-9c8dc456","/zh-CN/options/Addons/Mixed/Ghoul.html",{"title":"Ghoul"},[":md"]],
  ["v-0e21e758","/zh-CN/options/Addons/Mixed/Gravestone.html",{"title":"Gravestone"},[":md"]],
  ["v-45f1aaf6","/zh-CN/options/Addons/Mixed/Guesser.html",{"title":"Guesser"},[":md"]],
  ["v-9b5dbe22","/zh-CN/options/Addons/Mixed/Rebound.html",{"title":"Rebound"},[":md"]],
  ["v-2d1eefe3","/zh-CN/options/Addons/Mixed/Schizophrenic.html",{"title":"Schizophrenic"},[":md"]],
  ["v-5460e201","/zh-CN/options/Addons/Mixed/Stubborn.html",{"title":"Stubborn"},[":md"]],
  ["v-367b824d","/zh-CN/options/Crewmates/Killing/Bastion.html",{"title":"Bastion"},[":md"]],
  ["v-52ed8f12","/zh-CN/options/Crewmates/Killing/Bodyguard.html",{"title":"Bodyguard"},[":md"]],
  ["v-88a3c000","/zh-CN/options/Crewmates/Killing/Crusader.html",{"title":"Crusader"},[":md"]],
  ["v-620b9f20","/zh-CN/options/Crewmates/Killing/Deceiver.html",{"title":"Deceiver"},[":md"]],
  ["v-12d34554","/zh-CN/options/Crewmates/Killing/Jailer.html",{"title":"Jailer"},[":md"]],
  ["v-0de54cbe","/zh-CN/options/Crewmates/Killing/Judge.html",{"title":"Judge"},[":md"]],
  ["v-e4275d60","/zh-CN/options/Crewmates/Killing/Knight.html",{"title":"Knight"},[":md"]],
  ["v-316f822e","/zh-CN/options/Crewmates/Killing/NiceGuesser.html",{"title":"Nice Guesser"},[":md"]],
  ["v-e99fce1c","/zh-CN/options/Crewmates/Killing/Retributionist.html",{"title":"Retributionist"},[":md"]],
  ["v-e7a7ef6e","/zh-CN/options/Crewmates/Killing/Reverie.html",{"title":"Reverie"},[":md"]],
  ["v-5d3c78ee","/zh-CN/options/Crewmates/Killing/Sheriff.html",{"title":"Sheriff"},[":md"]],
  ["v-2a897f16","/zh-CN/options/Crewmates/Killing/Veteran.html",{"title":"Veteran"},[":md"]],
  ["v-3b9f3c60","/zh-CN/options/Crewmates/Killing/VIgilante.html",{"title":"Vigilante"},[":md"]],
  ["v-70081f73","/zh-CN/options/Crewmates/Power/Copycat.html",{"title":"Copycat"},[":md"]],
  ["v-1c6c511c","/zh-CN/options/Crewmates/Power/Dictator.html",{"title":"Dictator"},[":md"]],
  ["v-6200230d","/zh-CN/options/Crewmates/Power/Guardian.html",{"title":"Guardian"},[":md"]],
  ["v-b46bafb6","/zh-CN/options/Crewmates/Power/Lookout.html",{"title":"Lookout"},[":md"]],
  ["v-e9a443a0","/zh-CN/options/Crewmates/Power/Marshall.html",{"title":"Marshall"},[":md"]],
  ["v-d6c6ae68","/zh-CN/options/Crewmates/Power/Mayor.html",{"title":"Mayor"},[":md"]],
  ["v-597f3af2","/zh-CN/options/Crewmates/Power/Monarch.html",{"title":"Monarch"},[":md"]],
  ["v-1c46e48b","/zh-CN/options/Crewmates/Power/Overseer.html",{"title":"Overseer"},[":md"]],
  ["v-aa6652d8","/zh-CN/options/Crewmates/Power/President.html",{"title":"President"},[":md"]],
  ["v-223106aa","/zh-CN/options/Crewmates/Power/Swapper.html",{"title":"Swapper"},[":md"]],
  ["v-459a8468","/zh-CN/options/Crewmates/Power/Telecommunication.html",{"title":"Telecommunication"},[":md"]],
  ["v-f9546d84","/zh-CN/options/Crewmates/Support/Chameleon.html",{"title":"Chameleon"},[":md"]],
  ["v-353eb390","/zh-CN/options/Crewmates/Support/Coroner.html",{"title":"Coroner"},[":md"]],
  ["v-50f482dd","/zh-CN/options/Crewmates/Support/Deputy.html",{"title":"Deputy"},[":md"]],
  ["v-40b979d5","/zh-CN/options/Crewmates/Support/Detective.html",{"title":"Detective"},[":md"]],
  ["v-24fec4cd","/zh-CN/options/Crewmates/Support/Enigma.html",{"title":"Enigma"},[":md"]],
  ["v-0a5451aa","/zh-CN/options/Crewmates/Support/FortuneTeller.html",{"title":"Fortune Teller"},[":md"]],
  ["v-31a701eb","/zh-CN/options/Crewmates/Support/Grenadier.html",{"title":"Grenadier"},[":md"]],
  ["v-d539011a","/zh-CN/options/Crewmates/Support/Inspector.html",{"title":"Inspector"},[":md"]],
  ["v-e0f92432","/zh-CN/options/Crewmates/Support/Lighter.html",{"title":"Lighter"},[":md"]],
  ["v-03e73af8","/zh-CN/options/Crewmates/Support/Mechanic.html",{"title":"Mechanic"},[":md"]],
  ["v-505c4864","/zh-CN/options/Crewmates/Support/Medic.html",{"title":"Medic"},[":md"]],
  ["v-48b0de1a","/zh-CN/options/Crewmates/Support/Medium.html",{"title":"Medium"},[":md"]],
  ["v-42161a80","/zh-CN/options/Crewmates/Support/Merchant.html",{"title":"Merchant"},[":md"]],
  ["v-7365ee1c","/zh-CN/options/Crewmates/Support/Mortician.html",{"title":"Mortician"},[":md"]],
  ["v-d9fe3b1c","/zh-CN/options/Crewmates/Support/Observer.html",{"title":"Observer"},[":md"]],
  ["v-5758808a","/zh-CN/options/Crewmates/Support/Oracle.html",{"title":"Oracle"},[":md"]],
  ["v-a9ed6126","/zh-CN/options/Crewmates/Support/Pacifist.html",{"title":"Pacifist"},[":md"]],
  ["v-bb022d56","/zh-CN/options/Crewmates/Support/Psychic.html",{"title":"Psychic"},[":md"]],
  ["v-ea392306","/zh-CN/options/Crewmates/Support/Snitch.html",{"title":"Snitch"},[":md"]],
  ["v-3fe776e6","/zh-CN/options/Crewmates/Support/Spiritualist.html",{"title":"Spiritualist"},[":md"]],
  ["v-5f0b688e","/zh-CN/options/Crewmates/Support/Spy.html",{"title":"Spy"},[":md"]],
  ["v-6bbeffaa","/zh-CN/options/Crewmates/Support/TimeManager.html",{"title":"Time Manager"},[":md"]],
  ["v-169f14ce","/zh-CN/options/Crewmates/Support/TimeMaster.html",{"title":"Time Master"},[":md"]],
  ["v-79bd07dc","/zh-CN/options/Crewmates/Support/Tracker.html",{"title":"Tracker"},[":md"]],
  ["v-d4d5529e","/zh-CN/options/Crewmates/Support/Witness.html",{"title":"Witness"},[":md"]],
  ["v-a77d93e4","/zh-CN/options/Crewmates/Vanilla/Crewmate.html",{"title":"Crewmate"},[":md"]],
  ["v-68c08d25","/zh-CN/options/Crewmates/Vanilla/Engineer.html",{"title":"Engineer"},[":md"]],
  ["v-7e4b54c6","/zh-CN/options/Crewmates/Vanilla/Scientist.html",{"title":"Scientist"},[":md"]],
  ["v-46478e28","/zh-CN/options/Experimental/Addon/Fool.html",{"title":"Fool"},[":md"]],
  ["v-a66fb35a","/zh-CN/options/Experimental/Addon/OiiaiCat.html",{"title":"Oiiai Cat"},[":md"]],
  ["v-16b6c8e3","/zh-CN/options/Experimental/Addon/YouTuber.html",{"title":"YouTuber"},[":md"]],
  ["v-252755ac","/zh-CN/options/Experimental/Crewmate/Admirer.html",{"title":"Admirer"},[":md"]],
  ["v-59e63442","/zh-CN/options/Experimental/Crewmate/Investigator.html",{"title":"Investigator"},[":md"]],
  ["v-16c035c6","/zh-CN/options/Experimental/Impostor/Blackmailer.html",{"title":"Blackmailer"},[":md"]],
  ["v-643bc154","/zh-CN/options/Experimental/Impostor/Butcher.html",{"title":"Butcher"},[":md"]],
  ["v-78837bb8","/zh-CN/options/Experimental/Impostor/Disperser.html",{"title":"Disperser"},[":md"]],
  ["v-6df24b5d","/zh-CN/options/Experimental/Impostor/Eraser.html",{"title":"Eraser"},[":md"]],
  ["v-1e80aea1","/zh-CN/options/Experimental/Impostor/Hangman.html",{"title":"Hangman"},[":md"]],
  ["v-7b4dc734","/zh-CN/options/Experimental/Impostor/KillingMachine.html",{"title":"Killing Machine"},[":md"]],
  ["v-3dbb5cbf","/zh-CN/options/Experimental/Impostor/Lightning.html",{"title":"Lightning"},[":md"]],
  ["v-daf86ffa","/zh-CN/options/Experimental/Impostor/Zombie.html",{"title":"Zombie"},[":md"]],
  ["v-1887a532","/zh-CN/options/Experimental/Neutral/Doppelganger.html",{"title":"Doppelganger"},[":md"]],
  ["v-56e7545d","/zh-CN/options/Experimental/Neutral/God.html",{"title":"God"},[":md"]],
  ["v-60e1351d","/zh-CN/options/Experimental/Neutral/Spiritcaller.html",{"title":"Spiritcaller"},[":md"]],
  ["v-208310c9","/zh-CN/options/Impostors/Concealing/Escapist.html",{"title":"Escapist"},[":md"]],
  ["v-3a05000a","/zh-CN/options/Impostors/Concealing/Mastermind.html",{"title":"Mastermind"},[":md"]],
  ["v-e737d0b8","/zh-CN/options/Impostors/Concealing/Miner.html",{"title":"Miner"},[":md"]],
  ["v-27a67765","/zh-CN/options/Impostors/Concealing/Puppeteer.html",{"title":"Puppeteer"},[":md"]],
  ["v-68249edd","/zh-CN/options/Impostors/Concealing/Scavenger.html",{"title":"Scavenger"},[":md"]],
  ["v-233d03e0","/zh-CN/options/Impostors/Concealing/Shapemaster.html",{"title":"Shapemaster"},[":md"]],
  ["v-fc5ad5a4","/zh-CN/options/Impostors/Concealing/SoulCatcher.html",{"title":"Soul Catcher"},[":md"]],
  ["v-9f7306ec","/zh-CN/options/Impostors/Concealing/Swooper.html",{"title":"Swooper"},[":md"]],
  ["v-59c1c9c2","/zh-CN/options/Impostors/Concealing/Trickster.html",{"title":"Trickster"},[":md"]],
  ["v-4d8edc1c","/zh-CN/options/Impostors/Concealing/Undertaker.html",{"title":"Undertaker"},[":md"]],
  ["v-69bf64f5","/zh-CN/options/Impostors/Concealing/Vampire.html",{"title":"Vampire"},[":md"]],
  ["v-4870bb95","/zh-CN/options/Impostors/Concealing/Vampiress.html",{"title":"Vampiress"},[":md"]],
  ["v-45d52c10","/zh-CN/options/Impostors/Concealing/Warlock.html",{"title":"Warlock"},[":md"]],
  ["v-41efc7ef","/zh-CN/options/Impostors/Concealing/Wildling.html",{"title":"Wildling"},[":md"]],
  ["v-58013e22","/zh-CN/options/Impostors/Hindering/Anonymous.html",{"title":"Anonymous"},[":md"]],
  ["v-48c1bf00","/zh-CN/options/Impostors/Hindering/Dazzler.html",{"title":"Dazzler"},[":md"]],
  ["v-597b1892","/zh-CN/options/Impostors/Hindering/Devourer.html",{"title":"Devourer"},[":md"]],
  ["v-22e93fb4","/zh-CN/options/Impostors/Hindering/Pitfall.html",{"title":"Pitfall"},[":md"]],
  ["v-f0656730","/zh-CN/options/Impostors/Hindering/Twister.html",{"title":"Twister"},[":md"]],
  ["v-ed5f2d24","/zh-CN/options/Impostors/Killing/Arrogance.html",{"title":"Arrogance"},[":md"]],
  ["v-f06f836a","/zh-CN/options/Impostors/Killing/Bard.html",{"title":"Bard"},[":md"]],
  ["v-4b2bd362","/zh-CN/options/Impostors/Killing/Berserker.html",{"title":"Berserker"},[":md"]],
  ["v-6f6fa7a6","/zh-CN/options/Impostors/Killing/Bomber.html",{"title":"Bomber"},[":md"]],
  ["v-1d31e231","/zh-CN/options/Impostors/Killing/BountyHunter.html",{"title":"Bounty Hunter"},[":md"]],
  ["v-86f6bc3a","/zh-CN/options/Impostors/Killing/Chronomancer.html",{"title":"Chronomancer"},[":md"]],
  ["v-7cc56864","/zh-CN/options/Impostors/Killing/Councillor.html",{"title":"Councillor"},[":md"]],
  ["v-26f2ef18","/zh-CN/options/Impostors/Killing/CursedWolf.html",{"title":"Cursed Wolf"},[":md"]],
  ["v-21395f40","/zh-CN/options/Impostors/Killing/Deathpact.html",{"title":"Deathpact"},[":md"]],
  ["v-1a921b66","/zh-CN/options/Impostors/Killing/EvilGuesser.html",{"title":"Evil Guesser"},[":md"]],
  ["v-6b734d72","/zh-CN/options/Impostors/Killing/EvilTracker.html",{"title":"Evil Tracker"},[":md"]],
  ["v-0bb08608","/zh-CN/options/Impostors/Killing/Greedy.html",{"title":"Greedy"},[":md"]],
  ["v-1e49e628","/zh-CN/options/Impostors/Killing/Inhibitor.html",{"title":"Inhibitor"},[":md"]],
  ["v-7e2c79bc","/zh-CN/options/Impostors/Killing/Instigator.html",{"title":"Instigator"},[":md"]],
  ["v-6dfae283","/zh-CN/options/Impostors/Killing/Ludopath.html",{"title":"Ludopath"},[":md"]],
  ["v-419ee566","/zh-CN/options/Impostors/Killing/Lurker.html",{"title":"Lurker"},[":md"]],
  ["v-c727f400","/zh-CN/options/Impostors/Killing/Mercenary.html",{"title":"Mercenary"},[":md"]],
  ["v-78857b6c","/zh-CN/options/Impostors/Killing/Ninja.html",{"title":"Ninja"},[":md"]],
  ["v-489a6325","/zh-CN/options/Impostors/Killing/Nuker.html",{"title":"Nuker"},[":md"]],
  ["v-25e8cc5d","/zh-CN/options/Impostors/Killing/QuickShooter.html",{"title":"Quick Shooter"},[":md"]],
  ["v-6672e013","/zh-CN/options/Impostors/Killing/Saboteur.html",{"title":"Saboteur"},[":md"]],
  ["v-146d520d","/zh-CN/options/Impostors/Killing/Sniper.html",{"title":"Sniper"},[":md"]],
  ["v-09445722","/zh-CN/options/Impostors/Killing/Spellcaster.html",{"title":"Spellcaster"},[":md"]],
  ["v-6ab01e41","/zh-CN/options/Impostors/Killing/Trapster.html",{"title":"Trapster"},[":md"]],
  ["v-65d48ff8","/zh-CN/options/Impostors/Killing/Underdog.html",{"title":"Underdog"},[":md"]],
  ["v-6b5173ee","/zh-CN/options/Impostors/Madmate/Crewpostor.html",{"title":"Crewpostor"},[":md"]],
  ["v-ddb96634","/zh-CN/options/Impostors/Madmate/Parasite.html",{"title":"Parasite"},[":md"]],
  ["v-97f629de","/zh-CN/options/Impostors/Support/AntiAdminer.html",{"title":"Anti Adminer"},[":md"]],
  ["v-c5608286","/zh-CN/options/Impostors/Support/Camouflager.html",{"title":"Camouflager"},[":md"]],
  ["v-1a53bf55","/zh-CN/options/Impostors/Support/Cleaner.html",{"title":"Cleaner"},[":md"]],
  ["v-70a4f682","/zh-CN/options/Impostors/Support/Consigliere.html",{"title":"Consigliere"},[":md"]],
  ["v-3d297973","/zh-CN/options/Impostors/Support/Fireworker.html",{"title":"Fireworker"},[":md"]],
  ["v-47fac0e6","/zh-CN/options/Impostors/Support/Gangster.html",{"title":"Gangster"},[":md"]],
  ["v-a764081a","/zh-CN/options/Impostors/Support/Godfather.html",{"title":"Godfather"},[":md"]],
  ["v-71394f8d","/zh-CN/options/Impostors/Support/Morphling.html",{"title":"Morphling"},[":md"]],
  ["v-2cc5e21d","/zh-CN/options/Impostors/Support/Nemesis.html",{"title":"Nemesis"},[":md"]],
  ["v-36504262","/zh-CN/options/Impostors/Support/TimeThief.html",{"title":"Time Thief"},[":md"]],
  ["v-608ccf6e","/zh-CN/options/Impostors/Support/Vindicator.html",{"title":"Vindicator"},[":md"]],
  ["v-4a35b84b","/zh-CN/options/Impostors/Support/Visionary.html",{"title":"Visionary"},[":md"]],
  ["v-eceb67e8","/zh-CN/options/Impostors/Vanilla/Impostor.html",{"title":"Impostor"},[":md"]],
  ["v-82c02bb6","/zh-CN/options/Impostors/Vanilla/Shapeshifter.html",{"title":"Shapeshifter"},[":md"]],
  ["v-20c64e6f","/zh-CN/options/Neutrals/Chaos/Collector.html",{"title":"Collector"},[":md"]],
  ["v-29d0c8cc","/zh-CN/options/Neutrals/Chaos/Cultist.html",{"title":"Cultist"},[":md"]],
  ["v-c6ce8ea2","/zh-CN/options/Neutrals/Chaos/Phantom.html",{"title":"Phantom"},[":md"]],
  ["v-8dd4f206","/zh-CN/options/Neutrals/Chaos/Pirate.html",{"title":"Pirate"},[":md"]],
  ["v-0490e18a","/zh-CN/options/Neutrals/Chaos/Provocateur.html",{"title":"Provocateur"},[":md"]],
  ["v-81cf354a","/zh-CN/options/Neutrals/Chaos/Revolutionist.html",{"title":"Revolutionist"},[":md"]],
  ["v-2e8d71c2","/zh-CN/options/Neutrals/Chaos/SoulCollector.html",{"title":"Soul Collector"},[":md"]],
  ["v-161f1ea6","/zh-CN/options/Neutrals/Chaos/Terrorist.html",{"title":"Terrorist"},[":md"]],
  ["v-78af9e53","/zh-CN/options/Neutrals/Chaos/Vector.html",{"title":"Vector"},[":md"]],
  ["v-4c0f3cbb","/zh-CN/options/Neutrals/Chaos/Vulture.html",{"title":"Vulture"},[":md"]],
  ["v-5c8d1de7","/zh-CN/options/Neutrals/Chaos/Workaholic.html",{"title":"Workaholic"},[":md"]],
  ["v-7bf94dad","/zh-CN/options/Neutrals/Evil/CursedSoul.html",{"title":"Cursed Soul"},[":md"]],
  ["v-eaecdb1e","/zh-CN/options/Neutrals/Evil/Doomsayer.html",{"title":"Doomsayer"},[":md"]],
  ["v-6286fc7b","/zh-CN/options/Neutrals/Evil/Executioner.html",{"title":"Executioner"},[":md"]],
  ["v-2af90f38","/zh-CN/options/Neutrals/Evil/Innocent.html",{"title":"Innocent"},[":md"]],
  ["v-4af64549","/zh-CN/options/Neutrals/Evil/Jester.html",{"title":"Jester"},[":md"]],
  ["v-281d3e2a","/zh-CN/options/Neutrals/Evil/Masochist.html",{"title":"Masochist"},[":md"]],
  ["v-77502fa6","/zh-CN/options/Neutrals/Evil/Seeker.html",{"title":"Seeker"},[":md"]],
  ["v-40e047bd","/zh-CN/options/Neutrals/Evil/Sunnyboy.html",{"title":"Sunnyboy"},[":md"]],
  ["v-f9c05f1a","/zh-CN/options/Neutrals/Killing/Agitator.html",{"title":"Agitator"},[":md"]],
  ["v-69ddf59e","/zh-CN/options/Neutrals/Killing/Arsonist.html",{"title":"Arsonist"},[":md"]],
  ["v-06242eda","/zh-CN/options/Neutrals/Killing/Bandit.html",{"title":"Bandit"},[":md"]],
  ["v-eba1c6de","/zh-CN/options/Neutrals/Killing/BloodKnight.html",{"title":"Blood Knight"},[":md"]],
  ["v-66f5a08d","/zh-CN/options/Neutrals/Killing/Demon.html",{"title":"Demon"},[":md"]],
  ["v-96bebe36","/zh-CN/options/Neutrals/Killing/Glitch.html",{"title":"Glitch"},[":md"]],
  ["v-29b975db","/zh-CN/options/Neutrals/Killing/HexMaster.html",{"title":"Hex Master"},[":md"]],
  ["v-07207ae0","/zh-CN/options/Neutrals/Killing/Huntsman.html",{"title":"Huntsman"},[":md"]],
  ["v-2ab60c41","/zh-CN/options/Neutrals/Killing/Infectious.html",{"title":"Infectious"},[":md"]],
  ["v-70a89af0","/zh-CN/options/Neutrals/Killing/Jackal.html",{"title":"Jackal"},[":md"]],
  ["v-2ca9b0de","/zh-CN/options/Neutrals/Killing/Jinx.html",{"title":"Jinx"},[":md"]],
  ["v-29795dd0","/zh-CN/options/Neutrals/Killing/Juggernaut.html",{"title":"Juggernaut"},[":md"]],
  ["v-48f78323","/zh-CN/options/Neutrals/Killing/Medusa.html",{"title":"Medusa"},[":md"]],
  ["v-342569f9","/zh-CN/options/Neutrals/Killing/Necromancer.html",{"title":"Necromancer"},[":md"]],
  ["v-bea4d3c8","/zh-CN/options/Neutrals/Killing/Occultist.html",{"title":"Occultist"},[":md"]],
  ["v-efde598c","/zh-CN/options/Neutrals/Killing/Pelican.html",{"title":"Pelican"},[":md"]],
  ["v-053cf43a","/zh-CN/options/Neutrals/Killing/Pickpocket.html",{"title":"Pickpocket"},[":md"]],
  ["v-2911c5f2","/zh-CN/options/Neutrals/Killing/Plaguebearer.html",{"title":"Plaguebearer"},[":md"]],
  ["v-6189a025","/zh-CN/options/Neutrals/Killing/Poisoner.html",{"title":"Poisoner"},[":md"]],
  ["v-3bf0e0f6","/zh-CN/options/Neutrals/Killing/PotionMaster.html",{"title":"Potion Master"},[":md"]],
  ["v-90da2aba","/zh-CN/options/Neutrals/Killing/Pyromaniac.html",{"title":"Pyromaniac"},[":md"]],
  ["v-61a7b7fb","/zh-CN/options/Neutrals/Killing/SerialKiller.html",{"title":"Serial Killer"},[":md"]],
  ["v-82dbe78e","/zh-CN/options/Neutrals/Killing/Shroud.html",{"title":"Shroud"},[":md"]],
  ["v-a0b13868","/zh-CN/options/Neutrals/Killing/Stalker.html",{"title":"Stalker"},[":md"]],
  ["v-eea989f2","/zh-CN/options/Neutrals/Killing/Traitor.html",{"title":"Traitor"},[":md"]],
  ["v-3284cfbb","/zh-CN/options/Neutrals/Killing/Virus.html",{"title":"Virus"},[":md"]],
  ["v-3beae572","/zh-CN/options/Neutrals/Killing/Werewolf.html",{"title":"Werewolf"},[":md"]],
  ["v-271dfd63","/zh-CN/options/Neutrals/Killing/Wraith.html",{"title":"Wraith"},[":md"]],
  ["v-1c7ce670","/zh-CN/options/Neutrals/Benign/Amnesiac.html",{"title":"Amnesiac"},[":md"]],
  ["v-785d00e5","/zh-CN/options/Neutrals/Benign/Follower.html",{"title":"Follower"},[":md"]],
  ["v-2bb607b2","/zh-CN/options/Neutrals/Benign/Hater.html",{"title":"Hater"},[":md"]],
  ["v-54861b84","/zh-CN/options/Neutrals/Benign/Imitator.html",{"title":"Imitator"},[":md"]],
  ["v-4993fd3f","/zh-CN/options/Neutrals/Benign/Lawyer.html",{"title":"Lawyer"},[":md"]],
  ["v-4de67ce1","/zh-CN/options/Neutrals/Benign/Maverick.html",{"title":"Maverick"},[":md"]],
  ["v-2db47c40","/zh-CN/options/Neutrals/Benign/Opportunist.html",{"title":"Opportunist"},[":md"]],
  ["v-e8fac4d8","/zh-CN/options/Neutrals/Benign/Pixie.html",{"title":"Pixie"},[":md"]],
  ["v-ac89deda","/zh-CN/options/Neutrals/Benign/Pursuer.html",{"title":"Pursuer"},[":md"]],
  ["v-ab53291c","/zh-CN/options/Neutrals/Benign/Romantic.html",{"title":"Romantic"},[":md"]],
  ["v-4471d642","/zh-CN/options/Neutrals/Benign/RomanticRuthless.html",{"title":"Ruthless Romantic"},[":md"]],
  ["v-6ccab29c","/zh-CN/options/Neutrals/Benign/RomanticVengeful.html",{"title":"Vengeful Romantic"},[":md"]],
  ["v-da09f756","/zh-CN/options/Neutrals/Benign/Shaman.html",{"title":"Shaman"},[":md"]],
  ["v-6d69cbfa","/zh-CN/options/Neutrals/Benign/Taskinator.html",{"title":"Taskinator"},[":md"]],
  ["v-61b92848","/zh-CN/options/Neutrals/Benign/Witch.html",{"title":"Witch"},[":md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
