import comp from "C:/Users/moebs/OneDrive/Bureau/Dev Tools/Among Us/Vuepress Site TOHE/docs/.vuepress/.temp/pages/translations/zh-CN/AboutUs.html.vue"
const data = JSON.parse("{\"path\":\"/translations/zh-CN/AboutUs.html\",\"title\":\"About Our Team\",\"lang\":\"en-US\",\"frontmatter\":{\"lang\":\"en-US\",\"title\":\"About Our Team\",\"contributors\":false},\"headers\":[{\"level\":2,\"title\":\"President\",\"slug\":\"president\",\"link\":\"#president\",\"children\":[]},{\"level\":2,\"title\":\"Co-President\",\"slug\":\"co-president\",\"link\":\"#co-president\",\"children\":[]},{\"level\":2,\"title\":\"Website Assistant\",\"slug\":\"website-assistant\",\"link\":\"#website-assistant\",\"children\":[]},{\"level\":2,\"title\":\"Department Heads\",\"slug\":\"department-heads\",\"link\":\"#department-heads\",\"children\":[]},{\"level\":2,\"title\":\"Staff Team\",\"slug\":\"staff-team\",\"link\":\"#staff-team\",\"children\":[]},{\"level\":2,\"title\":\"TOHE Team\",\"slug\":\"tohe-team\",\"link\":\"#tohe-team\",\"children\":[{\"level\":3,\"title\":\"Lead Developer\",\"slug\":\"lead-developer\",\"link\":\"#lead-developer\",\"children\":[]},{\"level\":3,\"title\":\"Contributors\",\"slug\":\"contributors\",\"link\":\"#contributors\",\"children\":[]}]},{\"level\":2,\"title\":\"Translators\",\"slug\":\"translators\",\"link\":\"#translators\",\"children\":[{\"level\":3,\"title\":\"Russian\",\"slug\":\"russian\",\"link\":\"#russian\",\"children\":[]},{\"level\":3,\"title\":\"Chinese\",\"slug\":\"chinese\",\"link\":\"#chinese\",\"children\":[]},{\"level\":3,\"title\":\"Spanish\",\"slug\":\"spanish\",\"link\":\"#spanish\",\"children\":[]},{\"level\":3,\"title\":\"Brazilian (Portuguese Brazil)\",\"slug\":\"brazilian-portuguese-brazil\",\"link\":\"#brazilian-portuguese-brazil\",\"children\":[]},{\"level\":3,\"title\":\"French\",\"slug\":\"french\",\"link\":\"#french\",\"children\":[]},{\"level\":3,\"title\":\"Japanese\",\"slug\":\"japanese\",\"link\":\"#japanese\",\"children\":[]},{\"level\":3,\"title\":\"Latam (Latin American)\",\"slug\":\"latam-latin-american\",\"link\":\"#latam-latin-american\",\"children\":[]},{\"level\":3,\"title\":\"Italian\",\"slug\":\"italian\",\"link\":\"#italian\",\"children\":[]},{\"level\":3,\"title\":\"Dutch\",\"slug\":\"dutch\",\"link\":\"#dutch\",\"children\":[]},{\"level\":3,\"title\":\"German\",\"slug\":\"german\",\"link\":\"#german\",\"children\":[]},{\"level\":3,\"title\":\"Portuguese (Portuguese Portugal)\",\"slug\":\"portuguese-portuguese-portugal\",\"link\":\"#portuguese-portuguese-portugal\",\"children\":[]}]},{\"level\":2,\"title\":\"MVPs\",\"slug\":\"mvps\",\"link\":\"#mvps\",\"children\":[]},{\"level\":2,\"title\":\"Original Creator\",\"slug\":\"original-creator\",\"link\":\"#original-creator\",\"children\":[]}],\"git\":{\"updatedTime\":1723308213000,\"contributors\":[{\"name\":\"Pyro\",\"email\":\"btriche.sots@gmail.com\",\"commits\":10},{\"name\":\"Moe\",\"email\":\"moebstergaming@hotmail.com\",\"commits\":1}]},\"filePathRelative\":\"translations/zh-CN/AboutUs.md\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
