<template><div><h1 id="installation-guide-to-tohe-on-steam" tabindex="-1"><a class="header-anchor" href="#installation-guide-to-tohe-on-steam"><span><font color=#f0b6d5>Installation Guide to TOHE on: <font color=#14356a>Steam</font></font></span></a></h1>
<p>It appears you want to install TOHE on Steam! Lucky for you, you're in the right place.<br>
Follow these simple steps, and TOHE will be working in no-time at all! Itch.io is roughly the exact same process as Steam, hence sharing a page.</p>
<p>Notice: You can follow the installation video <a href="https://www.youtube.com/watch?v=2oyD75caFQ0" target="_blank" rel="noopener noreferrer">HERE<ExternalLinkIcon/></a> if you want visuals with steps. However, the below steps work just fine.</p>
<h3 id="step-1-download-the-latest-release" tabindex="-1"><a class="header-anchor" href="#step-1-download-the-latest-release"><span><font color=#f0b6d5><font color=#14356a>Step 1:</font> Download the Latest Release</font></span></a></h3>
<p>Download the latest full Release of Town of Host: Enhanced in our Discord at <code v-pre>#tohe-release</code>, or on our GitHub <a href="https://github.com/0xDrMoe/TownofHost-Enhanced/releases/latest" target="_blank" rel="noopener noreferrer">Here<ExternalLinkIcon/></a>. (Make sure you install the <code v-pre>TOH-Enhanced-SteamEpic-2.2.0.zip</code> &amp; not <code v-pre>TOH-Enhanced-XboxApp-2.2.0.zip</code>.)</p>
<h3 id="step-2-extract-the-mod-folder" tabindex="-1"><a class="header-anchor" href="#step-2-extract-the-mod-folder"><span><font color=#f0b6d5><font color=#14356a>Step 2:</font> Extract the Mod Folder</font></span></a></h3>
<p>Once the download is complete, extract it into a new empty folder somewhere, like on the desktop.</p>
<h3 id="step-3-copy-paste-your-mod-files-into-game-directory" tabindex="-1"><a class="header-anchor" href="#step-3-copy-paste-your-mod-files-into-game-directory"><span><font color=#f0b6d5><font color=#14356a>Step 3:</font> Copy + Paste your Mod Files into Game Directory</font></span></a></h3>
<p>Locate your AmongUs install. For example, if you own the game on Steam, you can find this by right clicking on the game in your library, selecting <i>Manage</i>, and finally selecting <i>Browse local files.</i><br>
<img src="@source/images/SteamGetFolder.png" alt="image"></p>
<p>Select all of the files in your Among Us installation and copy them to the folder that now has the files from the TOHE release. The folder should now look something like this:<br>
<img src="@source/images/ResultFolder.png" alt="image"></p>
<h3 id="step-4-run-among-us-to-set-up-the-mod" tabindex="-1"><a class="header-anchor" href="#step-4-run-among-us-to-set-up-the-mod"><span><font color=#f0b6d5><font color=#14356a>Step 4:</font> Run Among Us to Set Up the Mod</font></span></a></h3>
<p>Within the TOHE folder, run <i>Among Us.exe</i>. The first time running it may take some time while the mod sets up its files. If you see a black screen, just wait a couple minutes. Once it finishes loading, you should get a popup with TOHE news. If you do not see anything about TOHE, double check that your files are all in the same folder.<br>
Note: If you separated your TOHE Mod and Vanilla folders, and run into an issue where it says 'you are logged out/in offline mode', close TOHE and open Steam, then try again. This should solve the issue. (Separating your folders isn't required, but recommended so your mod instance still works if a major Among Us update is released.)</p>
<h3 id="step-5-create-a-shortcut-optional" tabindex="-1"><a class="header-anchor" href="#step-5-create-a-shortcut-optional"><span><font color=#f0b6d5><font color=#14356a>Step 5:</font> Create a Shortcut <font color=#ed3d52>[OPTIONAL]</font></font></span></a></h3>
<p>Right click your <i>Among Us.exe</i> file and click <i>Create shortcut</i>. Then, move the new shortcut to a location that’s easy for you to access, such as your Desktop.</p>
<h4 id="if-you-are-running-into-issues-please-refer-to-the-troubleshooting-page-for-troubleshooting" tabindex="-1"><a class="header-anchor" href="#if-you-are-running-into-issues-please-refer-to-the-troubleshooting-page-for-troubleshooting"><span>If you are running into issues, please refer to the <RouteLink to="/Troubleshooting.html">Troubleshooting</RouteLink> page for troubleshooting!</span></a></h4>
<h3 id="you-have-now-installed-town-of-host-enhanced-on-steam-now-it-s-time-to-set-up-tohe" tabindex="-1"><a class="header-anchor" href="#you-have-now-installed-town-of-host-enhanced-on-steam-now-it-s-time-to-set-up-tohe"><span>You have now installed Town of Host: Enhanced on Steam! Now, it's time to Set-Up TOHE!</span></a></h3>
</div></template>


