<template><div><h1 id="installation-guide-to-tohe-on-thunderstore-mod-manager-r2modman" tabindex="-1"><a class="header-anchor" href="#installation-guide-to-tohe-on-thunderstore-mod-manager-r2modman"><span><font color=#f0b6d5>Installation Guide to TOHE on: <font color=#23FFB0>Thunderstore Mod Manager/r2modman</font></font></span></a></h1>
<p>Note: This also works for r2modman, which is essentially Thunderstore minus the annoying Overwolf part!</p>
<h3 id="step-1-download-and-install-thunderstore-mod-manager-or-r2modman" tabindex="-1"><a class="header-anchor" href="#step-1-download-and-install-thunderstore-mod-manager-or-r2modman"><span><font color=#f0b6d5><font color=#23FFB0>Step 1:</font> Download and Install Thunderstore Mod Manager or r2modman</font></span></a></h3>
<p>Download <a href="https://www.overwolf.com/app/thunderstore-thunderstore_mod_manager" target="_blank" rel="noopener noreferrer">Thunderstore Mod Manager<ExternalLinkIcon/></a> or <a href="https://thunderstore.io/package/ebkr/r2modman/" target="_blank" rel="noopener noreferrer">r2modman<ExternalLinkIcon/></a>.<br>
Note: If you select r2modman, choose the manual download.<br>
You can change the destination if you want, but that's not required. Once the download and installation is finished, open <b>Thunderstore Mod Manager</b>/<b>r2modman</b> (There should be an icon on your desktop, if not then check around in AppData).</p>
<h3 id="step-2-select-among-us-from-the-game-list" tabindex="-1"><a class="header-anchor" href="#step-2-select-among-us-from-the-game-list"><span><font color=#f0b6d5><font color=#23FFB0>Step 2:</font> Select Among Us from the Game List</font></span></a></h3>
<p>Search for <b>Among Us</b> on the supported games list. Click <i>Select game</i> &amp; select the platform that you're using to play Among Us, then wait for it to load the mod list.</p>
<h3 id="step-3-choose-or-create-a-profile-for-tohe" tabindex="-1"><a class="header-anchor" href="#step-3-choose-or-create-a-profile-for-tohe"><span><font color=#f0b6d5><font color=#23FFB0>Step 3:</font> Choose or Create a Profile for TOHE</font></span></a></h3>
<p>On the Profile Selection page, you can use the <i>Default</i> profile, or create a new one specifically for <b>TOHE</b>. Click <i>Select profile</i>, and use the sidebar to find <i>Get mods</i>.</p>
<h3 id="step-4-download-the-tohe-mod" tabindex="-1"><a class="header-anchor" href="#step-4-download-the-tohe-mod"><span><font color=#f0b6d5><font color=#23FFB0>Step 4:</font> Download the TOHE Mod</font></span></a></h3>
<p>Search for <b>TOHE</b>. Click the option by: <b><i>TheEnhancedNetwork</i></b> as this is the official version, and click <i>Download</i>. Once it finishes, use the sidebar to find <i>My mods</i>.</p>
<h3 id="step-5-select-modded-or-vanilla-mode" tabindex="-1"><a class="header-anchor" href="#step-5-select-modded-or-vanilla-mode"><span><font color=#f0b6d5><font color=#23FFB0>Step 5:</font> Select Modded or Vanilla Mode</font></span></a></h3>
<p>Near the top of your screen, click the <i>Modded</i> option. (Clicking <i>Vanilla</i> will launch Vanilla, self explanatory.)</p>
<h4 id="if-you-are-running-into-issues-please-refer-to-the-troubleshooting-page-for-troubleshooting" tabindex="-1"><a class="header-anchor" href="#if-you-are-running-into-issues-please-refer-to-the-troubleshooting-page-for-troubleshooting"><span>If you are running into issues, please refer to the <RouteLink to="/Troubleshooting.html">Troubleshooting</RouteLink> page for troubleshooting!</span></a></h4>
<h3 id="you-have-now-installed-town-of-host-enhanced-on-thunderstore-mod-manager-or-r2modman-now-it-s-time-to-set-up-tohe" tabindex="-1"><a class="header-anchor" href="#you-have-now-installed-town-of-host-enhanced-on-thunderstore-mod-manager-or-r2modman-now-it-s-time-to-set-up-tohe"><span>You have now installed Town of Host: Enhanced on Thunderstore Mod Manager &amp;/or r2modman! Now, it's time to Set-Up TOHE!</span></a></h3>
</div></template>


